/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.academico.views.matricula;

import ec.com.academico.dao.MatriculaJpaController;
import ec.com.academico.dao.ext.MatriculasExt;
import ec.com.academico.dao.ext.ObtenerDTO;
import ec.com.academico.dto.Cursos;
import ec.com.academico.dto.Matricula;
import ec.com.academico.dto.Paralelos;
import ec.com.academico.dto.RelCursoParalelo;
import ec.com.academico.dtoJoin.MatriculaJoin;
import ec.com.academico.util.ClaseReporte;
import ec.com.academico.util.EntityManagerUtil;
import ec.com.academico.util.Tablas;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Usuario
 */
public class ConsultaMatriculas extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaMatriculas
     */
    int x, y;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    String valor = "";
    List<Matricula> listMatric;
    List<MatriculaJoin> listMatriculaJoin;
    MatriculaJpaController mc = new MatriculaJpaController(EntityManagerUtil.obtenerEntityManager());

    MatriculasExt selectMatricula = new MatriculasExt();

    Matricula objMatri = new Matricula();

    public ConsultaMatriculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        cargarTbaMatriculados();
    }

    public void cargarTbaMatriculados() {
        listMatric = mc.findMatriculaEntities();
        Tablas.listarMatriculas(listMatric, TbaMatriculados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbaMatriculados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxFiltro = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TbaMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbaMatriculados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TbaMatriculadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TbaMatriculados);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/academico/iconos/Salir.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/academico/iconos/men_Matricula.png"))); // NOI18N
        jButton2.setText("MATRICULAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATRICULADOS");
        jLabel2.setOpaque(true);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE ...", "N° MATRICULA", "PERIODO LECTIVO", "ESTUDIANTE", "CURSO", "TODO", "PERIODO LECTIVO Y CURSO", " " }));

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/academico/iconos/imprimir.png"))); // NOI18N
        jButton4.setText("IMPRIMIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbaMatriculadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbaMatriculadosMousePressed
        int id = 0;
        if (evt.getClickCount() == 2) {

            id = TbaMatriculados.getSelectedRow();

            objMatri = devuelveObjeto(Long.valueOf(TbaMatriculados.getValueAt(id, 0).toString()), listMatric);
            if (objMatri != null) {

                ConsultaDetalleMatricula au = new ConsultaDetalleMatricula(new javax.swing.JFrame(), true, objMatri);
                au.setVisible(true);

            }
            cargarTbaMatriculados();
        }
    }//GEN-LAST:event_TbaMatriculadosMousePressed
    public Matricula devuelveObjeto(Long id, List<Matricula> listabod) {
        Matricula doc = null;
        for (int i = 0; i < listabod.size(); i++) {
            if (listabod.get(i).getIdMatricula().equals(id)) {
                doc = listabod.get(i);
                break;
            }
        }
        return doc;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AgregarMatricula au = new AgregarMatricula(new javax.swing.JFrame(), true);
        au.setVisible(true);
        cargarTbaMatriculados();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
//        valor = txtBuscar.getText();
//        Tablas.filtro(valor, TbaMatriculados);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        //        char c = evt.getKeyChar();
        //        if (Character.isSpaceChar(c)) {
        //            getToolkit().beep();
        //            evt.consume();
        //        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList tablac = new ArrayList();
        for (int i = 0; i < TbaMatriculados.getRowCount(); i++) {

            ClaseReporte tabla1 = new ClaseReporte(" " + TbaMatriculados.getValueAt(i, 0).toString(),
                    " " + TbaMatriculados.getValueAt(i, 1).toString(), " " + TbaMatriculados.getValueAt(i, 2).toString(),
                    " " + TbaMatriculados.getValueAt(i, 3).toString(), " " + TbaMatriculados.getValueAt(i, 4).toString());
//            Matricula mat = (Matricula) listMatric;
//                Matricula tabla1 = new Matricula(mat.getIdMatricula().toString(),mat.getIdEstudiante().toString()
//                        ,mat.getIdEstudiante().getNombres().toString());

            tablac.add(tabla1);

        }
        /**/
        try {
//            String dir = System.getProperty("user.dir") + "/Reportes/" + "ConsultaMatriculas.jasper";
//            String dir = System.getProperty("user.dir") + "/src/" + "/ec/" + "/com/" + "/academico/" + "/views/" + "/report/"
//                    + "ConsultaMatriculas.jasper";
            String dir = "/ec/com/academico/views/report/ConsultaMatriculas.jasper";
//            JasperReport reporte = (JasperReport) JRLoader.loadObject(dir);
            JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource(dir));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(tablac));
            JDialog frame = new JDialog(this);
            JRViewer viewer = new JRViewer(jprint);
            frame.add(viewer);
            frame.setSize(new Dimension(ancho / 2, 500));
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            viewer.setFitWidthZoomRatio();
        } catch (JRException ex) {
            Logger.getLogger(ConsultaMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        txtBuscar.setText(txtBuscar.getText().toUpperCase());
    }//GEN-LAST:event_txtBuscarFocusLost
    public void buscar() {
        String query = "";

        query = txtBuscar.getText();

        int pos = cbxFiltro.getSelectedIndex();
        if (pos == 0) {
            JOptionPane.showMessageDialog(null, "Seleccion una Opcion");
        }
        if (pos == 1) {
            //N° MATRICULA
            listMatric = mc.findMatriculaEntities();
            Tablas.listarMatriculasNumMatricula(listMatric, TbaMatriculados, query);

        }
        if (pos == 2) {
            //PERIODO LECTIVO
            listMatric = mc.findMatriculaEntities();
            Tablas.listarMatriculasPeriodoLectivo(listMatric, TbaMatriculados, query);
        }
        if (pos == 3) {
            //ESTUDIANTE
            listMatriculaJoin = selectMatricula.listarMatriculaEstu(query);
//        ListProdVent = selectProdVent.listarProductoVenta();
            Tablas.listarMatriculasEstudiante(listMatriculaJoin, TbaMatriculados);
        }
        if (pos == 4) {
            //Curso
//            query  = query.substring(5,10);  
            try {
                String curso = " ";
                String paralelo = " ";
                String[] arrSplit_2 = query.split(" ", 2);
                for (int i = 0; i < arrSplit_2.length; i++) {
                    curso = arrSplit_2[0];
                    paralelo = arrSplit_2[1];
                }
//            String curso = query.substring(0,5);
//            String paralelo = query.substring(6,9);
                listMatriculaJoin = selectMatricula.listarMatriculaCurso();
                Tablas.listarMatriculasCurso(listMatriculaJoin, TbaMatriculados, curso, paralelo);

            } catch (Exception e) {
            }
        }
        if (pos == 5) {
            //TODO
            listMatric = mc.findMatriculaEntities();
            Tablas.listarMatriculasTodo(listMatric, TbaMatriculados);

        }
        if (pos == 6) {
            //PERIODO LECTIVO Y CURSO 
            String periodo = null;
            String curso = null;
            String paralelo = null;
//            Long id_aula = null;
            String[] arrSplit_2 = query.split(" ", 3);
            for (int i = 0; i < arrSplit_2.length; i++) {
                periodo = arrSplit_2[0];
                curso = arrSplit_2[1];
                paralelo = arrSplit_2[2];
            }
//                System.out.println("periodo"+periodo);//
//                System.out.println("curso"+curso);//
//                System.out.println("paralelo"+paralelo);//
            Paralelos paralelos = ObtenerDTO.ObtenerParalelos(paralelo);
            Cursos cursos = ObtenerDTO.ObtenerCursos(curso);
//            System.out.println("parametros1:"+paralelos.getNombre());
//            System.out.println("parametros2:"+cursos.getNombre());
            RelCursoParalelo id_aula = ObtenerDTO.ObtenerRelCursosParalelos(cursos.getIdCursos(), paralelos.getIdParalelos());
//            System.out.println("envio;"+periodo+id_aula.getIdRelCursoParalelo());
            listMatriculaJoin = selectMatricula.listarMatriculaPeriodoLectivoCurso(periodo, id_aula.getIdRelCursoParalelo());
            Tablas.listarMatriculasEstudiante(listMatriculaJoin, TbaMatriculados);

        }

        txtBuscar.setText("");

//        Tablas.cargarFiltroProductosNota(t_Nota_faltantes, lista);
        query = "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaMatriculas dialog = new ConsultaMatriculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbaMatriculados;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
