/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.entrada.salida;

import ec.com.cp.controler.ctr_bitacoras;
import ec.com.cp.controler.ctr_co_cabecera_compra;
import ec.com.cp.controler.ctr_co_detalle_compra;
import ec.com.cp.controler.ctr_inv_inventario;
import ec.com.cp.model.join.model_emp_empresa_join;
import ec.com.cp.model.join.model_inv_inventario_join;
import ec.com.cp.model.join.model_seg_proveedor_join;
import ec.com.cp.model.join.model_seg_usuario_join;
import ec.com.cp.model.model_bit_entrada;
import ec.com.cp.model.model_co_cabecera_compra;
import ec.com.cp.model.model_co_detalle_compra;
import ec.com.cp.tabla.Tablas_compra;
import ec.com.cp.util.Formato_Numeros;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Entrada extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venta
     */
    model_inv_inventario_join objStock;
    int cantidad, cantidadModi, idCliente, id_uni, cantidadStock, Cont = 1;
    Double precio, precioIva, total, descuento, subtotal;
    Double VGTsubtotal, VGTtotal, VGTiva, VGTdescuento;
    /// cambiar a compra
    List<model_co_detalle_compra> listaDetCompra = new ArrayList<model_co_detalle_compra>();
//////////8
    List<model_inv_inventario_join> ListProdVent2 = null;
    ctr_inv_inventario selectProdVent2 = new ctr_inv_inventario();
///////////////////
    List<model_inv_inventario_join> ListProdVent = null;
    ctr_inv_inventario selectProdVent = new ctr_inv_inventario();

//    ArrayList<model_seg_cliente_join> listCliente;
//    ctr_seg_cliente crudCliente = new ctr_seg_cliente();
    model_seg_proveedor_join objProveedor;
//
    model_emp_empresa_join objEmpresa;
    model_seg_usuario_join objUsuario;
//cambiar a compra
    ctr_co_cabecera_compra crudCabCompra = new ctr_co_cabecera_compra();
    ctr_co_detalle_compra crudDetalleCompra = new ctr_co_detalle_compra();
//

    ctr_inv_inventario crudInv = new ctr_inv_inventario();
    List<model_inv_inventario_join> listaInventario;
//bitacora
    ctr_bitacoras crudBitacora = new ctr_bitacoras();

    public Entrada() {
        initComponents();
    }

    public Entrada(java.awt.Frame parent, boolean modal, model_emp_empresa_join empresa, model_seg_usuario_join usuario) {
        initComponents();
        this.setLocation(250, 15);
        objEmpresa = empresa;
        objUsuario = usuario;
        cargarDatosEmp();
//        consumidorFinal();
    }

    public void cargarDatosEmp() {
        txt_empresa.setText(objEmpresa.getNombre_comercial());
    }
//    public void cargarDatosEmp() {
//        txt_empresa.setText(objEmpresa.getNombre_comercial());
//    }

//    public void CargarCliente2() {
//        listCliente = crudCliente.listarClientesCedula(1, txtIdentificacion.getText());
//        for (int i = 0; i < listCliente.size(); i++) {
//            txtIdentificacion.setText(listCliente.get(i).getCedula());
////            txtApellido.setText(listCliente.get(i).getNombre());
//            txtNombre.setText(listCliente.get(i).getNombre());
//            txt_idCliente.setText(listCliente.get(i).getId_persona().toString());
//            txtEmail.setText(listCliente.get(i).getEmail());
//            txtTelefono.setText(listCliente.get(i).getTelefono());
//            txtCelular.setText(listCliente.get(i).getCelular());
//            txtDireccion.setText(listCliente.get(i).getDireccion());
//        }
////        Tablas.listarClientes(listCliente, tba_Clientes);0930981110
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id_proveedor = new javax.swing.JTextField();
        txt_empresa = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbx_documento = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tba_detalle_venta = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtIva = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_agregar_prod = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DATOS DEL PROVEEDOR:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txt_id_proveedor.setEditable(false);

        txt_empresa.setEditable(false);
        txt_empresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empresaActionPerformed(evt);
            }
        });
        txt_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_empresaKeyTyped(evt);
            }
        });

        jButton4.setText("PROVEEDOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_nombre.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("NOMBRE:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Codigo:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("DIRECCION:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("TELEFONO: ");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("CORREO: ");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("CI/RUC");

        txtIdentificacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("DOCUMENTO :");

        cbx_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGRESO A BODEGA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(35, 35, 35)
                                    .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(22, 22, 22)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(41, 41, 41)
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_documento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(32, 32, 32)
                                .addComponent(txtEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                        .addGap(140, 140, 140))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DETALLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tba_detalle_venta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tba_detalle_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tba_detalle_venta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tba_detalle_venta.setRowHeight(20);
        tba_detalle_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tba_detalle_ventaMousePressed(evt);
            }
        });
        tba_detalle_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tba_detalle_ventaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tba_detalle_ventaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tba_detalle_venta);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel13.setText("SUBTOTAL: ");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel16.setText("DESCUENTO:");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel14.setText("IVA  : ");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL: ");

        txtTotal.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIva.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtIva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDescuento.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtDescuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSubtotal.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtSubtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToolBar1.setRollover(true);

        btn_agregar_prod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agregar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add32.png"))); // NOI18N
        btn_agregar_prod.setText("   AGREGAR   ");
        btn_agregar_prod.setFocusable(false);
        btn_agregar_prod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar_prod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agregar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_prodActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_agregar_prod);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_add_shopping_cart_128_28122.png"))); // NOI18N
        jButton3.setText("   REGISTRAR   ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualiza32.png"))); // NOI18N
        jButton2.setText("   NUEVO   ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar32.png"))); // NOI18N
        jButton1.setText("   SALIR   ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESO PRODUCTO");
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "OBSERVACION"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tba_detalle_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tba_detalle_ventaMousePressed
        int row = tba_detalle_venta.rowAtPoint(evt.getPoint());
        int col = tba_detalle_venta.columnAtPoint(evt.getPoint());
        if (evt.getClickCount() == 1) {
            if (tba_detalle_venta.getModel().getColumnClass(col).equals(JButton.class)) {
                try {
                    int r = JOptionPane.showConfirmDialog(null, "Desea eliminar este producto?", "", JOptionPane.YES_OPTION);
                    if (r == JOptionPane.YES_OPTION) {
                        int i = tba_detalle_venta.getSelectedRow();

                        listaDetCompra.remove(i);

                        Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);
                        Totalizar();
                        TotalizarIva();
                        TotalizarDescuento();
                        TotalizarSubtotal();
                        Cont = Cont - 1;
                        for (int j = 0; j < listaDetCompra.size(); j++) {
                            Cont = j + 1;
                            listaDetCompra.get(j).setLinea_detalle(Cont);
                        }
                    }
                } catch (Exception e) {
                }
            }
        }

    }//GEN-LAST:event_tba_detalle_ventaMousePressed

    private void tba_detalle_ventaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tba_detalle_ventaKeyReleased
        try {
//            char c = evt.getKeyChar();
//            if (c < '0' || c > '9') {
//                evt.consume();
//            } else {
            int i = tba_detalle_venta.getSelectedRow();
            Double descuentoT = 0.00;

            String valor = ""+tba_detalle_venta.getValueAt(i, 3);
            char o = valor.charAt(0);
            if (o < '0' || o > '9') {
                System.out.println("error " + o);
                JOptionPane.showMessageDialog(null, "Valor Incorrecto!");
                listaDetCompra.get(i).setCantidad(1);
                Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);

            } else {
                System.out.println("puedes ");
//            }
                int cantidadMod = Integer.valueOf(valor);

                cantidadModi = cantidadMod;
                Long id = (Long) tba_detalle_venta.getValueAt(i, 1);

                ListProdVent = selectProdVent.ListaInventarioJoinStockVenta();
                for (int j = 0; j < ListProdVent.size(); j++) {
                    if (ListProdVent.get(j).getId_producto().equals(id)) {
                        int ca = Integer.valueOf(ListProdVent.get(j).getCantidad().intValue());
//                        int out = cantidadMod.compareTo(ca);
//                        if (cantidadMod > ca) {
//                        int out = cantidadMod.compareTo(ca);
//                        if (out == 1) {
//                            JOptionPane.showMessageDialog(null, "Verifique Stock");
                            listaDetCompra.get(i).setCantidad(1);
                            Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);

//                        } else {
                            System.out.println("can t " + cantidadMod);
                            if (cantidadMod > 0) {
                                String ivaS = tba_detalle_venta.getValueAt(i, 6).toString();
                                Double ivaT = Double.valueOf(ivaS.replace(",", "."));
                                String precioS = tba_detalle_venta.getValueAt(i, 4).toString();
                                Double precioT = Double.valueOf(precioS.replace(",", "."));
//                        String descuentoS = tba_detalle.getValueAt(i, 5).toString();
//                        Double descuentoT = Double.valueOf(descuentoS.replace(",", "."));
                                ListProdVent2 = selectProdVent2.ListaInventarioJoinStockVenta();
                                for (int k = 0; k < ListProdVent2.size(); k++) {
//                            System.out.println("lista /// " + ListProdVent2.get(k).getValor_descuento());
                                    if (ListProdVent2.get(k).getId_producto() == ListProdVent.get(j).getId_producto()) {
//                                System.out.println("valor " + ListProdVent2.get(k).getValor_descuento());
                                        descuentoT = ListProdVent2.get(k).getValor_descuento();
                                    }
                                }

                                Double IvaMod = calcularIvaItemCantMod(cantidadModi, ivaT, precioT);
                                Double Desc = calcularDescuentoItemCantMod(cantidadModi, descuentoT);
                                Double subt = calcularSubtotalItemCantMod(cantidadModi, precioT);
                                Double total = calcularTotalItemCantMod(cantidadModi, IvaMod, Desc, precioT);

                                listaDetCompra.get(i).setCantidad(cantidadMod);
                                listaDetCompra.get(i).setIva(IvaMod);
                                listaDetCompra.get(i).setSub_total(subt);
                                listaDetCompra.get(i).setTotal(total);
                                listaDetCompra.get(i).setDecuento(Desc);
//                                Tablas.llenarDetalleVenta(tba_detalle, listaDetFactura);
                                Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);

                                Totalizar();
                                TotalizarIva();
                                TotalizarDescuento();
                                TotalizarSubtotal();
                                /**/

                            } else {
                                JOptionPane.showMessageDialog(null, "Valor Incorrecto!");
                                listaDetCompra.get(i).setCantidad(1);
                                Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);

                            }
                        }/**/

//                    }/**/

                }/**/
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tba_detalle_ventaKeyReleased
    private void Totalizar() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetCompra.get(i).getTotal();
                t += p;
//                Formato_Numeros.formatoNumero(t.toString());
                VGTtotal = t;
                txtTotal.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtTotal.setText(t.toString());
            }
        }
    }

    private void TotalizarIva() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetCompra.get(i).getIva();
                t += p;
//                t=Double.valueOf(Formato_Numeros.formatoNumero(t.toString()));
                VGTiva = t;
                txtIva.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtIva.setText(t.toString());
            }
        }
    }

    private void TotalizarDescuento() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetCompra.get(i).getDecuento();
                t += p;
//                Formato_Numeros.formatoNumero(t.toString());
                VGTdescuento = t;
                txtDescuento.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtDescuento.setText(t.toString());
            }
        }
    }

    private void TotalizarSubtotal() {
        Double t = 0.0;
        Double p = 0.0;
        Double pre = 0.0;
        int cant;
        Double subtotal = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                pre = listaDetCompra.get(i).getPrecio_unitario();
                cant = listaDetCompra.get(i).getCantidad();

                p = listaDetCompra.get(i).getSub_total();
                t += p;
                VGTsubtotal = t;
                txtSubtotal.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtSubtotal.setText(t.toString());
            }
        }
    }

    public Double calcularIvaItemCantMod(int cantMod, Double posicionIva, Double posicionPrecio) {

//        BigInteger cant;
        Double pre;
        Double precioIva2 = null;
        String aplica = objStock.getIva_string();

        if (posicionIva != 0.0) {
//            cant = cantidad;
            pre = posicionPrecio;
            precioIva2 = (cantMod * pre) * 12 / 100;
        } else {
            precioIva2 = 0.0;
        }
        return precioIva2;
    }

    public Double calcularDescuentoItemCantMod(int cantMod, Double descuento) {
        Double descuent = null;
        descuent = cantMod * descuento;
        return descuent;
    }

    public Double calcularSubtotalItemCantMod(int cantMod, Double PrecioIva) {
        Double subto = null;
        subto = cantMod * PrecioIva;
        return subto;
    }

    public Double calcularTotalItemCantMod(int cantMod, Double PrecioIva, Double desc, Double precio) {

        Double pre;
        Double total2;
        /**/
        pre = precio;
        total2 = (cantMod * pre) + PrecioIva - desc;

        return total2;
    }
    private void tba_detalle_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tba_detalle_ventaKeyTyped

    }//GEN-LAST:event_tba_detalle_ventaKeyTyped
    public String validarProductos(String datos) {
        String obj1 = "no";

        for (int i = 0; i < listaDetCompra.size(); i++) {

            if (datos.equals("" + (listaDetCompra.get(i).getId_producto()))) {
                obj1 = "si";

                break;
            }

        }

        return obj1;

    }    public Double calcularIvaItem() {
        int cant;
        Double pre;
        Double precioIva = null;
        String aplica = objStock.getIva_string();
        if (aplica.equals("SI")) {
            cant = cantidad;
            pre = precio;
            System.out.println("precio " + pre);
            precioIva = (cant * pre) * 12 / 100;
        } else {
            precioIva = 0.0;
        }
        return precioIva;
    }

    public Double calcularSubtotal() {
        int cant;
        Double pre;
        Double subt;
        cant = cantidad;
        pre = precio;
        subt = cant * pre;

        return subt;
    }

    public Double calcularTotalItem() {
        int cant;
        Double pre;
        Double preIva;
        Double total2;
        Double desc;
        /**/
        preIva = calcularIvaItem();
        cant = cantidad;
        pre = precio;
        desc = descuento;
        total2 = (cant * pre) + preIva - desc;

        return total2;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged

    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

    }//GEN-LAST:event_jLabel1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txt_id_proveedor.getText() == null) {
            JOptionPane.showMessageDialog(null, "SELECCIONE PROVEEDOR!");
        } else {
            if ("0.0".equals(txtTotal.getText())) {
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS!");
            } else {
                int r = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Ingresar Productos?", "", JOptionPane.YES_NO_OPTION);
                if (r == JOptionPane.YES_OPTION) {
                    java.util.Date date = new java.util.Date();

                    java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                    java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
                    model_co_cabecera_compra cabComp = new model_co_cabecera_compra();

                    cabComp.setId_proveedor(Long.valueOf(txt_id_proveedor.getText()));
                    cabComp.setId_sucursal(objEmpresa.getId_sucursal());
                    cabComp.setEstado("A");
//                cabFact.setForma_pago(cbx_FormaPago.getSelectedItem().toString());
                    cabComp.setTotal_subtotal(VGTsubtotal);
                    cabComp.setTotal_iva(VGTiva);
                    cabComp.setTotal_descuento(VGTdescuento);
                    cabComp.setTotal_facturado(VGTtotal);
                    cabComp.setUsuario_creacion(objUsuario.getNomb_usuario());
                    cabComp.setF_creacion(sqlTime);

                    Long c = crudCabCompra.insertarCabeceraVenta(cabComp, 1);
                    try {
                        for (int i = 0; i < listaDetCompra.size(); i++) {
                            model_co_detalle_compra detalleCompra = new model_co_detalle_compra();
                            detalleCompra.setLinea_detalle(listaDetCompra.get(i).getLinea_detalle());
                            detalleCompra.setId_producto(listaDetCompra.get(i).getId_producto());
                            detalleCompra.setCantidad(listaDetCompra.get(i).getCantidad());
                            detalleCompra.setDescripcion(listaDetCompra.get(i).getDescripcion());
                            detalleCompra.setPrecio_unitario(listaDetCompra.get(i).getPrecio_unitario());
                            detalleCompra.setSub_total(listaDetCompra.get(i).getSub_total());
                            detalleCompra.setIva(listaDetCompra.get(i).getIva());
                            detalleCompra.setDecuento(listaDetCompra.get(i).getDecuento());
                            detalleCompra.setTotal(listaDetCompra.get(i).getTotal());
                            detalleCompra.setEstado(listaDetCompra.get(i).getEstado());

                            String out = crudDetalleCompra.insertarDetalleCompra(detalleCompra/*, Long.valueOf(txt_id_proveedor.getText()),
                                    objEmpresa.getId_sucursal(), VGTtotal, sqlTime.toString()*/);
                            guardarKardex(detalleCompra.getId_producto(), listaDetCompra.get(i).getCantidad());
                            /*ingreso a tabla*/
                            model_bit_entrada bitacora = new model_bit_entrada();
                            bitacora.setId_producto(listaDetCompra.get(i).getId_producto());
                            bitacora.setCantidad(listaDetCompra.get(i).getCantidad());
                            bitacora.setUsuario_ingreso(objUsuario.getNomb_usuario());
                            bitacora.setTipoDocumento(cbx_documento.getSelectedItem().toString());
                            String msnEntrada = crudBitacora.insertarBitacoraEntrada(bitacora);
                            System.out.println("BITACORA:" + msnEntrada);
                            /*Bitacora Entrada*/
                            JOptionPane.showMessageDialog(null, out);
                        }
                    } catch (Exception e) {
                    }

                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empresaActionPerformed

    private void txt_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_empresaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empresaKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ConsultaProveedor cp = new ConsultaProveedor(new javax.swing.JFrame(), true);
            cp.setVisible(true);
            objProveedor = cp.obtenerObjProveedor();

            txt_id_proveedor.setText(objProveedor.getId_usuario().toString());
            txtIdentificacion.setText(objProveedor.getCedula());
            txt_nombre.setText(objProveedor.getNombre_comercial());
//            txt_idCliente.setText(objCliente.getId_persona().toString());
            txtEmail.setText(objProveedor.getEmail());
            txtTelefono.setText(objProveedor.getTelefono());
//            txtCelular.setText(objCliente.getCelular());
            txtDireccion.setText(objProveedor.getDireccion());
//            txtTipoIdent.setText(Clientes.getIdTipoIndentificacion().getNombreIdentificacion());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed
    public void CargarProveedor() {
//        listCliente = crudCliente.listarClientesCedula(1, txtIdentificacion.getText());
//        for (int i = 0; i < listCliente.size(); i++) {
//            txtIdentificacion.setText(listCliente.get(i).getCedula());
////            txtApellido.setText(listCliente.get(i).getNombre());
////            txtNombre.setText(listCliente.get(i).getNombre());
////            txt_idCliente.setText(listCliente.get(i).getId_persona().toString());
//            txtEmail.setText(listCliente.get(i).getEmail());
//            txtTelefono.setText(listCliente.get(i).getTelefono());
////            txtCelular.setText(listCliente.get(i).getCelular());
//            txtDireccion.setText(listCliente.get(i).getDireccion());
//        }
////        Tablas.listarClientes(listCliente, tba_Clientes);0930981110
    }
    private void txtIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CargarProveedor();
        }
    }//GEN-LAST:event_txtIdentificacionKeyPressed

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped

    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed
    public void limpiar() {
//        consumidorFinal();
        listaDetCompra.clear();
        Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);
//        Tablas.llenarDetalleVenta(tba_detalle, listaDetFactura);
        txtSubtotal.setText("");
        txtDescuento.setText("");
        txtIva.setText("");
        txtTotal.setText("");
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_agregar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_prodActionPerformed
        try {
            StockMovimiento ingre = new StockMovimiento(new javax.swing.JFrame(), true);
            ingre.setVisible(true);

            objStock = ingre.obtObjProdVent();
            if (objStock == null) {
                JOptionPane.showMessageDialog(rootPane, "SELECCIONE!");
            } else {
                if (validarProductos("" + (objStock.getId_producto())).equals("si")) {
                    JOptionPane.showMessageDialog(rootPane, "El producto ya se fue seleccionado!");
                } else {
                    model_co_detalle_compra detalle = new model_co_detalle_compra();
                    cantidad = 1;
                    precio = objStock.getValor_venta();
                    precioIva = calcularIvaItem();
                    descuento = objStock.getValor_descuento();
                    System.out.println(" " + precioIva);
                    detalle.setId_producto(objStock.getId_producto());
                    detalle.setDescripcion(objStock.getNombre_producto());
                    detalle.setCantidad(cantidad);
                    detalle.setDecuento(descuento);
                    detalle.setIva(precioIva);
                    detalle.setPrecio_unitario(objStock.getValor_costo());
                    subtotal = calcularSubtotal();
                    total = calcularTotalItem();
                    detalle.setSub_total(subtotal);
                    detalle.setTotal(total);
                    detalle.setEstado("A");

                    listaDetCompra.add(detalle);
                    for (int i = 0; i < listaDetCompra.size(); i++) {
                        Cont = i + 1;
                        detalle.setLinea_detalle(Cont);
                    }

                    Tablas_compra.llenarDetalleCompra(tba_detalle_venta, listaDetCompra);
                    Totalizar();
                    TotalizarIva();
                    TotalizarDescuento();
                    TotalizarSubtotal();
                }
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_agregar_prodActionPerformed
    public void guardarKardex(Long id, int cantVent) {
        int Sumcantidad = 0;
        listaInventario = crudInv.ListaInventarioJoinTodo();
        for (int i = 0; i < listaInventario.size(); i++) {
            if (listaInventario.get(i).getId_producto().equals(id)) {
                int Stock = listaInventario.get(i).getCantidad().intValue();
                /*operancion de Stock*/
                Sumcantidad = Stock + cantVent;
                System.out.println("Stock :" + Stock);
                System.out.println("cantVent :" + cantVent);
                System.out.println("Suma :" + Sumcantidad);
            }
        }

        objStock.setCantidad(Long.valueOf(Sumcantidad));
        objStock.setId_producto(id);
        String cant = crudInv.ActualizarCantidadVenta(objStock, 1);
    }

//    public void consumidorFinal() {
//        listCliente = crudCliente.listarClientes(1);
//        for (int i = 0; i < listCliente.size(); i++) {
//            System.out.println("+" + listCliente.get(i).getId_persona());
//            if (listCliente.get(i).getId_persona() == 1) {
//                System.out.println("**");
//                txtIdentificacion.setText(listCliente.get(i).getCedula());
//                txtNombre.setText(listCliente.get(i).getNombre());
//                txt_idCliente.setText(listCliente.get(i).getId_persona().toString());
//                txtEmail.setText(listCliente.get(i).getEmail());
//                txtTelefono.setText(listCliente.get(i).getTelefono());
//                txtCelular.setText(listCliente.get(i).getCelular());
//                txtDireccion.setText(listCliente.get(i).getDireccion());
//
//            }
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_prod;
    private javax.swing.JComboBox<String> cbx_documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tba_detalle_venta;
    private javax.swing.JLabel txtDescuento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JLabel txtIva;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
