/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.presentacion;

import ec.com.cp.controler.ctr_pdt_articulo;
import ec.com.cp.controler.ctr_pdt_categoria;
import ec.com.cp.controler.ctr_pdt_presentacion;
import ec.com.cp.controler.ctr_pdt_subcategoria;
import ec.com.cp.model.model_pdt_articulo;
import ec.com.cp.model.model_pdt_categoria;
import ec.com.cp.model.model_pdt_envase;
import ec.com.cp.model.model_pdt_medida;
import ec.com.cp.model.model_pdt_presentacion;
import ec.com.cp.model.join.model_pdt_subcategoria_join_subcategoria;
import ec.com.cp.model.model_pdt_articulo_dos;
import ec.com.cp.model.model_pdt_marca_dos;
import ec.com.cp.modelEXT.ObtenerModel;
import ec.com.cp.view.categoria.agregarCategoria;
import ec.com.cp.view.subcategoria.agregarSubCategorias;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class agregarPresentacion extends javax.swing.JDialog {

    int x, y;
    ctr_pdt_categoria crud = new ctr_pdt_categoria();
    ArrayList<model_pdt_categoria> listCategoria;
    int idCategoria = 0;
    int idSubCategoria = 0;
    int idMarca = 0;
    /**/
    ctr_pdt_subcategoria crudsub = new ctr_pdt_subcategoria();
    ArrayList<model_pdt_subcategoria_join_subcategoria> listSubCategoria;
    /**/
    model_pdt_articulo articulo = new model_pdt_articulo();
    ctr_pdt_articulo crudart = new ctr_pdt_articulo();
    ArrayList<model_pdt_articulo> listArticulo;
    /**/
    ctr_pdt_presentacion crudpre = new ctr_pdt_presentacion();
    model_pdt_presentacion presentacion = new model_pdt_presentacion();

    model_pdt_medida objmedida = new model_pdt_medida();

    public agregarPresentacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCbxCategoria();
        txt_articulo.setEnabled(false);
        txt_marca.setEnabled(false);
    }

    public void cargarCbxCategoria() {

//        cbx_categoria.removeAllItems();
        listCategoria = crud.listarCategorias(1);
        for (int i = 0; i < listCategoria.size(); i++) {
            if (listCategoria.get(i).getEstado() == 'A') {
                cbx_categoria.addItem(listCategoria.get(i).getNombre());
            }
        }
    }

    public void cagarCbxSubcategoria(int id) {

        cbx_subcategoria.removeAllItems();
        listSubCategoria = crudsub.listarSubCategoriasIdcategoria(id);
        for (int i = 0; i < listSubCategoria.size(); i++) {
            cbx_subcategoria.addItem(listSubCategoria.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_categoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbx_subcategoria = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_articulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_medida = new javax.swing.JTextField();
        txt_envase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESENTACION");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar32.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disquete guardar 32.png"))); // NOI18N
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ARTICULO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CATEGORIA:");

        cbx_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_categoriaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SUBCATEGORIA:");

        cbx_subcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_subcategoriaActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_articulo.setText("SELECCIONE...");
        txt_articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_articuloMousePressed(evt);
            }
        });
        txt_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_articuloActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PRESENTACION"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MEDIDA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ENVASE:");

        txt_medida.setText("SELECCIONE...");
        txt_medida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_medidaMousePressed(evt);
            }
        });
        txt_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_medidaActionPerformed(evt);
            }
        });

        txt_envase.setText("SELECCIONE...");
        txt_envase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_envaseMousePressed(evt);
            }
        });
        txt_envase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_envaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_medida, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txt_envase))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_envase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MARCA:");

        txt_marca.setText("SELECCIONE...");
        txt_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_marcaMousePressed(evt);
            }
        });
        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbx_subcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbx_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txt_articulo))))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_subcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        java.util.Date date = new java.util.Date();
//        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
//        java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
        model_pdt_medida med
                = ObtenerModel.ObtenerMedida(objmedida.getNombre_medida());
        model_pdt_envase env
                = ObtenerModel.ObtenerEnvase(txt_envase.getText());
        model_pdt_articulo_dos art
                = ObtenerModel.ObtenerArticulo(txt_articulo.getText());
        try {
            presentacion.setId_medida(med.getId_medida());
            presentacion.setId_envase(env.getId_envase());
            presentacion.setEstado('A');
            presentacion.setUsuario_creacion("YO");
            presentacion.setId_articulo(art.getId_articulo());

            String o = crudpre.insertarPresentacion(presentacion, 1);
            if (o.equals("GUARDADO EXITOSAMENTE")) {
                JOptionPane.showMessageDialog(null, o);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, o);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbx_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_categoriaActionPerformed
        try {
            model_pdt_categoria id = ObtenerModel.ObtenerCategoria(cbx_categoria.getSelectedItem().toString());
            idCategoria = id.getId_categoria().intValue();
            cagarCbxSubcategoria(idCategoria);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbx_categoriaActionPerformed

    private void cbx_subcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_subcategoriaActionPerformed
        try {
            if (!cbx_subcategoria.getSelectedItem().toString().equals("")) {
                txt_articulo.setEnabled(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbx_subcategoriaActionPerformed

    private void txt_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_articuloActionPerformed

    }//GEN-LAST:event_txt_articuloActionPerformed

    private void txt_articuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_articuloMousePressed
//        int i = 0;
//        String msg = null;
//        if (evt.getClickCount() == 1) {
//            model_pdt_subcategoria_join_subcategoria sub
//                    = ObtenerModel.ObtenerSubcategoria(cbx_subcategoria.getSelectedItem().toString());
//
//            idSubCategoria = sub.getId_subcategoria().intValue();
//            consultaArticuloEscoger c = new consultaArticuloEscoger(new javax.swing.JFrame(), true, idSubCategoria);
//            c.setVisible(true);
//            model_pdt_articulo obj = c.getObjeto();
//            txt_articulo.setText(obj.getNombre_articulo());
//            txt_marca.setEnabled(true);
//        }
        
        int i = 0;
        String msg = null;
        if (evt.getClickCount() == 1) {
            model_pdt_marca_dos sub
                    = ObtenerModel.ObtenerMarca(txt_marca.getText());

            idMarca = sub.getId_marca().intValue();
            System.out.println("id art " + idMarca);
            consultaArticuloEscojer c = new consultaArticuloEscojer(new javax.swing.JFrame(), true, idMarca);
            c.setVisible(true);
            model_pdt_articulo_dos obj = c.getObjeto();
            try {
                if (obj.getArticulo()!= null) {
                    txt_articulo.setText(obj.getArticulo());
                }
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_txt_articuloMousePressed

    private void txt_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_marcaMousePressed
//        int i = 0;
//        String msg = null;
//        if (evt.getClickCount() == 1) {
//            model_pdt_marca_dos sub
//                    = ObtenerModel.ObtenerMarca(txt_articulo.getText());
//
//            idMarca = sub.getId_marca().intValue();
//            System.out.println("id art " + idMarca);
//            consultaMarcaEscojer_ c = new consultaMarcaEscojer_(new javax.swing.JFrame(), true, idMarca);
//            c.setVisible(true);
//            model_pdt_marca_dos obj = c.getObjeto();
//            try {
//                if (obj.getNombre_marca()!= null) {
//                    txt_marca.setText(obj.getNombre_marca());
//                }
//            } catch (Exception e) {
//            }
//
//        }
//int i = 0;
//        String msg = null;
//        if (evt.getClickCount() == 1) {
//            model_pdt_subcategoria_join_subcategoria sub
//                    = ObtenerModel.ObtenerSubcategoria(cbx_subcategoria.getSelectedItem().toString());
//
//            idSubCategoria = sub.getId_subcategoria().intValue();
//            consultaMarcaEscojer_ c = new consultaMarcaEscojer_(new javax.swing.JFrame(), true, idSubCategoria);
//            c.setVisible(true);
//            model_pdt_marca_dos obj = c.getObjeto();
//            txt_marca.setText(obj.getNombre_marca());
//            txt_articulo.setEnabled(true);
//        }
    }//GEN-LAST:event_txt_marcaMousePressed

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void txt_medidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_medidaMousePressed
        int i = 0;
        String msg = null;
        if (evt.getClickCount() == 1) {

            consultaMedidaEscoger c = new consultaMedidaEscoger(new javax.swing.JFrame(), true);
            c.setVisible(true);
            try {
                 objmedida = c.obtenerObj();
                if (objmedida != null) {
                    txt_medida.setText(objmedida.getNombre_medida());
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txt_medidaMousePressed

    private void txt_envaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_envaseMousePressed
        int i = 0;
        String msg = null;
        if (evt.getClickCount() == 1) {

            ConsultaEnvaseEscoger c = new ConsultaEnvaseEscoger(new javax.swing.JFrame(), true);
            c.setVisible(true);

            model_pdt_envase obj = c.obtenerObj();
            txt_envase.setText(obj.getNombre_envase());
        }
    }//GEN-LAST:event_txt_envaseMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        agregarSubCategorias ga = new agregarSubCategorias(new javax.swing.JFrame(), true);
        ga.setVisible(true);
        cagarCbxSubcategoria(idCategoria);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        agregarCategoria ga = new agregarCategoria(new javax.swing.JFrame(), true);
        ga.setVisible(true);
        cbx_categoria.removeAllItems();
        cargarCbxCategoria();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_medidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_medidaActionPerformed

    private void txt_envaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_envaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_envaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregarPresentacion dialog = new agregarPresentacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_categoria;
    private javax.swing.JComboBox<String> cbx_subcategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_articulo;
    private javax.swing.JTextField txt_envase;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_medida;
    // End of variables declaration//GEN-END:variables
}
