/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.principal;

import ec.com.cp.view.entrada.Entrada_;
import ec.com.cp.entrada.salida.Entrada;
import ec.com.cp.entrada.salida.Salida;
import ec.com.cp.model.join.model_emp_empresa_join;
import ec.com.cp.model.join.model_seg_usuario_join;
import ec.com.cp.util.util_fondo;
import ec.com.cp.view.marca.consultaMarca;
import ec.com.cp.view.categoria.consultaCategoria;
import ec.com.cp.view.envase.FrmConsultaEnvase;
import ec.com.cp.view.inventario.FrmInventarioList;
import ec.com.cp.view.articulo.consultaArticulo;
import ec.com.cp.view.entrada.ConsultarEntrada_;
import ec.com.cp.view.entrada.reporte.ConsultarEntradaReporte;
import ec.com.cp.view.medida.consultaMedida;
import ec.com.cp.view.producto.consultaProducto;
import ec.com.cp.view.proveedor.FrmProveedorList;
import ec.com.cp.view.subcategoria.consultaSubcategoria;
import ec.com.cp.view.tarifario.ConsultaTarifario;
import ec.com.cp.view.usuario.FrmEmpleadoActivoList;
import ec.com.cp.view.usuario.FrmEmpleadoInactivoList;
import ec.com.cp.view.usuario.cuenta.FrmConfirmarClave;
import ec.com.cp.view.venta.Venta;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class FrmPrincipal extends javax.swing.JFrame {

//    Variables fondo = new Variables();
//    JoinEmpleados us = null;
//    Hilo hilo;
//    Crud c = new Crud();
//    bloqueo b = new bloqueo();
//    Validaciones val = new Validaciones();
    model_emp_empresa_join objEmpresa = null;
    model_seg_usuario_join objUsuario = null;

    public FrmPrincipal(model_seg_usuario_join usuario, model_emp_empresa_join empresa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
        objEmpresa = empresa;
        objUsuario = usuario;
        form();
//        this.setTitle(fondo.getTitle() + TITLE + "---USUARIO" + " ---" + us.getNombre_comercial_em() + "---");
        jDesktopPanel.add(new util_fondo(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height), BorderLayout.CENTER);
//        jToolBar1.setEnabled(false);
//        lbSucursal.setVisible(false);
//        lbEmpresa.setVisible(false);
//        lbIdUsuario.setVisible(false);
//        this.setIconImage(fondo.getIconoVentana());
//        System.out.println("usuario: " + usuario.getUsuario() + "   " + usuario.getId_usuario() + usuario.getId_empresa() + usuario.getId_sucursal());
//        lbEmpresa.setText(us.getId_empresa().toString());
//        lbSucursal.setText(us.getId_sucursal().toString());
//        lbIdUsuario.setText(us.getId_usuario().toString());
//        lbsuc.setText(us.getNombre_comercial_su());
//        lbUsuario.setText(us.getUsuario());
        permisos();
//        bloq();
//
//        Timer tiempo = new Timer(100, new FrmPrincipal.horas());
//        tiempo.start();
//
//        hilo = new Hilo(this);
//        hilo.start();
//        mens();

    }

    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPanel = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnContra = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnCalificacion = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbEmpresa = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meMantenimineto = new javax.swing.JMenu();
        Empresa = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenuItem();
        jmProveedor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        meVenta = new javax.swing.JMenu();
        jmVenta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        meArticulo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmAlumnos = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jmCalificacion = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jmMatriculas = new javax.swing.JMenuItem();
        meProducto = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jm_producto = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jDesktopPanel.setOpaque(false);

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnContra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contra 32.png"))); // NOI18N
        btnContra.setText("  ACTUALIZAR  ");
        btnContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContra.setFocusable(false);
        btnContra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnContra);

        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usaurio_32.png"))); // NOI18N
        btnUsuario.setText("  USUARIO  ");
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.setFocusable(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        btnCalificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto 32.png"))); // NOI18N
        btnCalificacion.setText("  PRODUCTO   ");
        btnCalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificacion.setFocusable(false);
        btnCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCalificacion);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajero.png"))); // NOI18N
        jButton3.setText("  SALIDA PRODUCTO  ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar documento 32.png"))); // NOI18N
        jButton2.setText("  GENERAR PEDIDO");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        lbEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmpresa.setText("jLabel1");

        hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText("EMPRESA:");
        hora.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hora.setVerifyInputWhenFocusTarget(false);

        lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("USUARIO:");
        lb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUsuario.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora)
                    .addComponent(lbEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb)
                    .addComponent(lbUsuario))
                .addContainerGap())
        );

        jDesktopPanel.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(694, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setMargin(new java.awt.Insets(4, 0, 4, 0));

        meMantenimineto.setText("MANTENIMIENTO");
        meMantenimineto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meMantenimineto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meMantenimineto.setMargin(new java.awt.Insets(3, 1, 3, 1));

        Empresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Empresa.setText("EMPRESA");
        Empresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaActionPerformed(evt);
            }
        });
        meMantenimineto.add(Empresa);

        jmUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmUsuarios.setText("USUARIOS");
        jmUsuarios.setBorderPainted(true);
        jmUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });
        meMantenimineto.add(jmUsuarios);

        jmProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmProveedor.setText("PROVEEDORES");
        jmProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProveedorActionPerformed(evt);
            }
        });
        meMantenimineto.add(jmProveedor);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("USUARIOS INACTIVOS");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        meMantenimineto.add(jMenuItem2);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem7.setText("ACTUALIZAR CLAVE");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        meMantenimineto.add(jMenuItem7);

        jMenuBar1.add(meMantenimineto);

        meVenta.setText("SALIDA");
        meVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmVenta.setText("GENERAR VENTA");
        jmVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVentaActionPerformed(evt);
            }
        });
        meVenta.add(jmVenta);

        jMenuBar1.add(meVenta);

        jMenu5.setText("ENTRADA");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setText("GENERAR PEDIDO");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setText("APROBAR PEDIDO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        meArticulo.setText("ARTICULO");
        meArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meArticulo.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenu1.setText("CLASIFICACION");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem10.setText("MEDIDA");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jmAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmAlumnos.setText("ARTICULO");
        jmAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jmAlumnos);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setText("ENVASE");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jmCalificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmCalificacion.setText("CATEGORIA");
        jmCalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCalificacionActionPerformed(evt);
            }
        });
        jMenu1.add(jmCalificacion);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem12.setText("SUB CATEGORIA");
        jMenuItem12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        meArticulo.add(jMenu1);

        jmMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmMatriculas.setText("CREAR ARTICULO");
        jmMatriculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMatriculasActionPerformed(evt);
            }
        });
        meArticulo.add(jmMatriculas);

        jMenuBar1.add(meArticulo);

        meProducto.setText("PRODUCTOS");
        meProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meProducto.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenu2.setText("CLASIFICACION");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem14.setText("CATEGORIA");
        jMenuItem14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem15.setText("SUBCATEGORIA");
        jMenuItem15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem17.setText("MARCA");
        jMenuItem17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem19.setText("MEDIDA");
        jMenuItem19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem20.setText("ENVASE");
        jMenuItem20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jm_producto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jm_producto.setText("PRODUCTO");
        jm_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jm_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jm_producto);

        meProducto.add(jMenu2);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem13.setText("PRECIOS");
        jMenuItem13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        meProducto.add(jMenuItem13);

        jMenuBar1.add(meProducto);

        jMenu4.setText("REPORTES");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem11.setText("INVENTARIO");
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("ENTRADA");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem9.setText("SALIDA");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("AYUDA");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("SALIR");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void form() {
//        java.util.Date sistFecha = new java.util.Date();
//        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
//        fecha.setText(formato.format(sistFecha));

        lbEmpresa.setText(objEmpresa.getNombre_comercial());
        lbUsuario.setText(objUsuario.getNomb_usuario());
        Empresa.setVisible(false);
        meArticulo.setVisible(false);
//        jDesktopPanel.setVisible(false);

//        jDesktopPanel.setBorder(new util_destock_panel_imagen());
    }

    class horas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            java.util.Date sistHora = new java.util.Date();
            String pmAm = "HH:mm:ss";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            java.util.Calendar hoy = java.util.Calendar.getInstance();
            hora.setText(String.format(format.format(sistHora), hoy));
        }
    }

    public void mens() {
//        String msg = c.HiloStatement2();
//        String salida="";
//        if ("M1".equals(msg)) {
//            salida="RENUEVE LA LICENCIA, QUEDAN CUATRO DIAS!";
//        }
//        if ("M2".equals(msg)) {
//            salida="RENUEVE LA LICENCIA, QUEDAN TRES DIAS!";
//        }
//        if ("M3".equals(msg)) {
//            salida="RENUEVE LA LICENCIA, QUEDAN DOS DIAS!";
//        }
//        if ("M4".equals(msg)) {
//            salida="RENUEVE LA LICENCIA, QUEDAN UN DIA!";
//        }
//        mensaje.setText(salida);
    }

    public void permisos() {
        String cargo = objUsuario.getRol();
        if ("ADMINISTRADOR".equals(cargo)) {

        } else {
            if ("GERENTE".equals(cargo)) {
                meMantenimineto.setVisible(false);
            }
            if ("SUPERVISOR".equals(cargo)) {
                meMantenimineto.setVisible(false);
                jmUsuarios.setVisible(false);
            }
            if ("COMPRA".equals(cargo)) {
                meVenta.setVisible(false);
                meMantenimineto.setVisible(false);
                jmUsuarios.setVisible(false);
            }
            if ("VENTA".equals(cargo)) {
                meProducto.setVisible(false);
                meMantenimineto.setVisible(false);
                jmUsuarios.setVisible(false);
            }
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿DESEA SALIR DEL SISTEMA?", "", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        FrmEmpleadoActivoList ne = new FrmEmpleadoActivoList(new javax.swing.JFrame(), true, objUsuario, objEmpresa);
        ne.setVisible(true);
    }//GEN-LAST:event_btnUsuarioActionPerformed


    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed
        FrmEmpleadoActivoList me = new FrmEmpleadoActivoList(new javax.swing.JFrame(), true, objUsuario, objEmpresa);
        me.setVisible(true);
    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmConfirmarClave cc = new FrmConfirmarClave(new javax.swing.JFrame(), true, objUsuario);
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrmConsultaEnvase mp = new FrmConsultaEnvase(new javax.swing.JFrame(), true/*, us*/);
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaActionPerformed
//        MostrarEmpresaUnoForm ae = new MostrarEmpresaUnoForm(new javax.swing.JFrame(), true, us);
//        ae.setVisible(true);
    }//GEN-LAST:event_EmpresaActionPerformed

    private void btnContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraActionPerformed
        FrmConfirmarClave cc = new FrmConfirmarClave(new javax.swing.JFrame(), true, objUsuario);
        cc.setVisible(true);
    }//GEN-LAST:event_btnContraActionPerformed

    private void jmMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMatriculasActionPerformed
//        MostrarMatriculasForm mm = new MostrarMatriculasForm(new javax.swing.JFrame(), true, us);
//        mm.setVisible(true);
    }//GEN-LAST:event_jmMatriculasActionPerformed

    private void jmAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnosActionPerformed
        consultaArticulo ma = new consultaArticulo(new javax.swing.JFrame(), true);
        ma.setVisible(true);
    }//GEN-LAST:event_jmAlumnosActionPerformed

    private void jmCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCalificacionActionPerformed
        consultaCategoria cc = new consultaCategoria(new javax.swing.JFrame(), true);
        cc.setVisible(true);
    }//GEN-LAST:event_jmCalificacionActionPerformed

    private void btnCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionActionPerformed
        consultaProducto cp = new consultaProducto(new javax.swing.JFrame(), true);
        cp.setVisible(true);
    }//GEN-LAST:event_btnCalificacionActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        consultaMedida mp = new consultaMedida(new javax.swing.JFrame(), true);
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        consultaSubcategoria cg = new consultaSubcategoria(new javax.swing.JFrame(), true);
        cg.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ConsultaTarifario ct = new ConsultaTarifario(new javax.swing.JFrame(), true);
        ct.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        consultaCategoria cc = new consultaCategoria(new javax.swing.JFrame(), true);
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        consultaSubcategoria cs = new consultaSubcategoria(new javax.swing.JFrame(), true);
        cs.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        consultaMarca ca = new consultaMarca(new javax.swing.JFrame(), true);
        ca.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jm_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_productoActionPerformed
        consultaProducto cm = new consultaProducto(new javax.swing.JFrame(), true);
        cm.setVisible(true);
    }//GEN-LAST:event_jm_productoActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        consultaMedida cme = new consultaMedida(new javax.swing.JFrame(), true);
        cme.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        FrmConsultaEnvase mp = new FrmConsultaEnvase(new javax.swing.JFrame(), true/*, us*/);
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jmVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVentaActionPerformed
        Venta facturacion = new Venta(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        jDesktopPanel.add(facturacion);
        facturacion.show();
    }//GEN-LAST:event_jmVentaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmEmpleadoInactivoList cme = new FrmEmpleadoInactivoList(new javax.swing.JFrame(), true, objUsuario, objEmpresa);
        cme.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Entrada_ ent = new Entrada_(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        jDesktopPanel.add(ent);
        ent.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Salida sal = new Salida(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        jDesktopPanel.add(sal);
        sal.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jmProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProveedorActionPerformed
        FrmProveedorList cme = new FrmProveedorList(new javax.swing.JFrame(), true, objUsuario, objEmpresa);
        cme.setVisible(true);
    }//GEN-LAST:event_jmProveedorActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
//        FrmInventarioListCuenca cin = new FrmInventarioListCuenca();
//        cin.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ConsultarEntradaReporte ent = new ConsultarEntradaReporte(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        ent.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Salida sal = new Salida(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        jDesktopPanel.add(sal);
        sal.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrmInventarioList cin = new FrmInventarioList(new javax.swing.JFrame(), true);
        cin.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ConsultarEntrada_ cin = new ConsultarEntrada_(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        cin.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Entrada_ ent = new Entrada_(new javax.swing.JFrame(), true, objEmpresa, objUsuario);
        jDesktopPanel.add(ent);
        ent.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Empresa;
    private javax.swing.JButton btnCalificacion;
    private javax.swing.JButton btnContra;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmAlumnos;
    private javax.swing.JMenuItem jmCalificacion;
    private javax.swing.JMenuItem jmMatriculas;
    private javax.swing.JMenuItem jmProveedor;
    private javax.swing.JMenuItem jmUsuarios;
    private javax.swing.JMenuItem jmVenta;
    private javax.swing.JMenuItem jm_producto;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenu meArticulo;
    private javax.swing.JMenu meMantenimineto;
    private javax.swing.JMenu meProducto;
    private javax.swing.JMenu meVenta;
    // End of variables declaration//GEN-END:variables
}
