/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.principal;

import ec.com.cp.controler.ctr_emp_empresa;
import ec.com.cp.model.join.model_emp_empresa_join;
import ec.com.cp.model.join.model_seg_usuario_join;
import ec.com.cp.model.model_emp_empresa;
import ec.com.cp.model.model_emp_sucursal;
import ec.com.cp.combo.combos_emp_empresa;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class FrmSeleccionSucursal extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     *
     * @param objeto
     */
    ctr_emp_empresa ctr = new ctr_emp_empresa();
    ArrayList<model_emp_empresa> empresa = null;
    ArrayList<model_emp_sucursal> sucursal = null;
    ArrayList<model_emp_empresa_join> ListEmpresa = null;
    model_emp_empresa_join objEmpresa = null;
    model_seg_usuario_join objUsuario = null;
    model_seg_usuario_join es = new model_seg_usuario_join();
    model_emp_empresa_join ej = new model_emp_empresa_join();

    public FrmSeleccionSucursal(model_seg_usuario_join objeto) {
        initComponents();
        setLocationRelativeTo(null);
        objUsuario = objeto;
        form();
    }

    public FrmSeleccionSucursal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbSucursal = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lbEmpresa = new javax.swing.JLabel();
        lbSucursal = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbEmpresa = new javax.swing.JComboBox<>();
        txtEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbSucursal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SUCURSAL..." }));
        cbSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalActionPerformed(evt);
            }
        });

        lbEmpresa.setText("empresa");

        lbSucursal.setText("sucursal");

        lbUsuario.setText("usuario");

        jLabel1.setText("            ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/base-de-datos 32.png"))); // NOI18N
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_32.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbEmpresa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE EMPRESA..." }));
        cbEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(lbEmpresa)
                .addGap(41, 41, 41)
                .addComponent(lbSucursal)
                .addGap(57, 57, 57)
                .addComponent(lbUsuario)
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(81, 81, 81)
                .addComponent(jButton2)
                .addGap(174, 174, 174))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpresa)
                    .addComponent(lbSucursal)
                    .addComponent(lbUsuario)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEmpresa.setText("jLabel2");
        txtEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSucursal, 0, 607, Short.MAX_VALUE)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(txtEmpresa)
                .addGap(32, 32, 32)
                .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmpresaActionPerformed
        int pos = cbEmpresa.getSelectedIndex();

        if (pos == 0) {
            JOptionPane.showMessageDialog(this, "ELIJA UNA EMPRESA");
            cbSucursal.setEnabled(false);
            cbSucursal.setSelectedIndex(0);
        } else {
            cbSucursal.setEnabled(true);
            es.setNomb_usuario(objUsuario.getNomb_usuario());
            es.setPassword(objUsuario.getPassword());
            sucursal = ctr.ComboSucursal(es);
            cbSucursal.setModel(combos_emp_empresa.ComboGetSucursal(sucursal));
            cbSucursal.setSelectedIndex(1);

            ej.setNombre_comercial(cbSucursal.getSelectedItem().toString());
            ListEmpresa = ctr.EmpresaJoin(ej);
        }
    }//GEN-LAST:event_cbEmpresaActionPerformed

    public model_emp_empresa_join ObjetoSucursal(String datos, ArrayList<model_emp_empresa_join> listarobj) {
        model_emp_empresa_join objeto1 = null;
        for (int i = 0; i < listarobj.size(); i++) {
            if (datos.equals(listarobj.get(i).getId_sucursal().toString())) {
                objeto1 = listarobj.get(i);
                break;
            }
        }
        return objeto1;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ingresarSistema();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void form(){
        lbUsuario.setText(objUsuario.getId_usuario().toString());
        lbEmpresa.setVisible(false);
        lbSucursal.setVisible(false);
        lbUsuario.setVisible(false);
        lbSucursal.setText(objUsuario.getId_sucursal().toString());
        lbSucursal.setText(objUsuario.getId_sucursal().toString());
        cbSucursal.setEnabled(false);
        empresa = ctr.ComboEmpresa();
        cbEmpresa.setModel(combos_emp_empresa.ComboGetEmpresa(empresa));
        cbEmpresa.setSelectedIndex(1);
        cbEmpresa.setVisible(false);
        
        String emp = cbEmpresa.getSelectedItem().toString();
        txtEmpresa.setText(emp);
//        txtEmpresa.setEditable(false);
    }
    
    public void ingresarSistema() {
        int po = cbEmpresa.getSelectedIndex();
        int po2 = cbSucursal.getSelectedIndex();
        if (po == 0) {
            JOptionPane.showMessageDialog(this, "ELIJA UNA EMPRESA");
        } else if (po2 == 0) {
            JOptionPane.showMessageDialog(this, "ELIJA UNA SUCURSAL");
        } else {
//            System.out.println("holaaaaa");
            objEmpresa = ObjetoSucursal(lbSucursal.getText(), ListEmpresa);
            if (objEmpresa != null) {
                FrmPrincipal acc = new FrmPrincipal(objUsuario, objEmpresa);
                acc.setVisible(true);
                this.dispose();
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void sucursal() {
//        JoinEmpleados is = new JoinEmpleados();
//        is.setUsuario(obj.getUsuario());
//        is.setContrasena(obj.getContrasena());
//        is.setNombre_comercial_su(cbSucursal.getSelectedItem().toString());
//        String a = crud.validarUsuario(is);
//        if (a == null) {
//            System.out.println("null");
//        } else {
//            lbUsuario.setText(a);
//            System.out.println("else" + a);
//        }
    }

    private void cbSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalActionPerformed
        sucursal();
    }//GEN-LAST:event_cbSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmSeleccionSucursal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JComboBox<String> cbSucursal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbSucursal;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel txtEmpresa;
    // End of variables declaration//GEN-END:variables
}
