package com.humtrusa.enumRecursos;

public enum EnumRecursosUMedidas {
	FILTROS_AGRUPADORES,
	AGRUPADOR_MARCAS,
	AGRUPADOR_LINEAS,
	AGRUPADOR_SUBLINEAS,
	AGRUPADOR_UMEDIDAS,
	LISTARMARCASFILTROS,
	LISTARLINEASFILTROS,
	LISTARSUBLINEASFILTROS,
	GUARDAR_MARCA,
	GUARDAR_LINEA,
	GUARDAR_SUBLINEA,
	GUARDAR_UMEDIDA
}
