package com.humtrusa.enumRecursos;

public enum EnumRecursosProveedores {
	LISTAR_PROVEEDORES_X_FILTROS,
	MANTENIMIENTO_PROVEEDORES,
	OBTENER_PROVEEDOR,
	AGRUPADOR_PROVEEDOR,
	ELIMINAR_PROVEEDOR;
	
}
