/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.producto;

import ec.com.cp.controler.ctr_gen_iva;
import ec.com.cp.controler.ctr_inv_bodega;
import ec.com.cp.controler.ctr_inv_inventario;
import ec.com.cp.controler.ctr_pdt_articulo;
import ec.com.cp.controler.ctr_pdt_categoria;
import ec.com.cp.controler.ctr_pdt_producto;
import ec.com.cp.controler.ctr_pdt_subcategoria;
import ec.com.cp.model.join.model_pdt_presentacion_join;
import ec.com.cp.model.join.model_pdt_producto_join;
import ec.com.cp.model.join.model_pdt_subcategoria_join_subcategoria;
import ec.com.cp.model.model_gen_bodega;
import ec.com.cp.model.model_gen_iva;
import ec.com.cp.model.model_pdt_articulo;
import ec.com.cp.model.model_pdt_categoria;
import ec.com.cp.model.model_pdt_marca;
import ec.com.cp.model.model_pdt_producto;
import ec.com.cp.modelEXT.ObtenerModel;
import ec.com.cp.view.categoria.agregarCategoria;
import ec.com.cp.view.subcategoria.agregarSubCategorias;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class agregarProductoCuenca extends javax.swing.JDialog {

    int x, y;
    ctr_pdt_categoria crud = new ctr_pdt_categoria();
    ArrayList<model_pdt_categoria> listCategoria;
    int idCategoria = 0;
    /**/
    ctr_pdt_subcategoria crudsub = new ctr_pdt_subcategoria();
    ArrayList<model_pdt_subcategoria_join_subcategoria> listSubCategoria;
    int idSubCategoria = 0;
    /**/
    model_pdt_articulo articulo = new model_pdt_articulo();
    ctr_pdt_articulo crudart = new ctr_pdt_articulo();
    model_pdt_articulo objArticulo;
    int idArticulo = 0;
    model_pdt_marca objMarca = new model_pdt_marca();
    int idMarca = 0;
    /**/
    model_pdt_producto producto = new model_pdt_producto();
    model_pdt_presentacion_join objPresentacion;
    ctr_pdt_producto crudProd = new ctr_pdt_producto();
    /**/
    ctr_gen_iva crudIva = new ctr_gen_iva();
    ArrayList<model_gen_iva> listIva;
    /**/

    ctr_inv_inventario crudInv = new ctr_inv_inventario();
    /**/

    ArrayList<model_gen_bodega> listBodega;
    ctr_inv_bodega crudBodega = new ctr_inv_bodega();
    
    public agregarProductoCuenca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
//        cbx_categoria.addItem("SELECCIONE...");
        cargarCbxCategoria();
        cagarCbxBodega();
        txt_articulo1.setEnabled(false);
        txt_marca1.setEnabled(false);
        txt_presentacion.setEnabled(false);
//        txt_medida12.setEnabled(false);
//        txt_envase1.setEnabled(false);
        btn_nombre.setEnabled(false);
    }

    public void cargarCbxCategoria() {
        listCategoria = crud.listarCategorias(1);
        for (int i = 0; i < listCategoria.size(); i++) {
            cbx_categoria11.addItem(listCategoria.get(i).getNombre());
        }
    }

    public void cagarCbxSubcategoria(int id) {

        cbx_subcategoria1.removeAllItems();
        listSubCategoria = crudsub.listarSubCategoriasIdcategoria(id);
        for (int i = 0; i < listSubCategoria.size(); i++) {
            cbx_subcategoria1.addItem(listSubCategoria.get(i).getNombre());
        }
    }
    public void cagarCbxBodega() {
        listBodega = crudBodega.ListarBodega();
        for (int i = 0; i < listBodega.size(); i++) {
            cbx_bodega.addItem(listBodega.get(i).getNombre_bodega());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbx_categoria11 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbx_subcategoria1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txt_articulo1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_descripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_nombre_productoConcadenado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_minimo = new javax.swing.JTextField();
        txt_maximo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_codigo_barra = new javax.swing.JTextField();
        cbx_bodega = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_marca1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbx_Iva = new javax.swing.JComboBox<>();
        btn_nombre = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_presentacion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel8.setBackground(new java.awt.Color(0, 51, 204));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRODUCTO ");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(254, 254, 254));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(1, 1, 1));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar32.png"))); // NOI18N
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(254, 254, 254));
        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(1, 1, 1));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disquete guardar 32.png"))); // NOI18N
        jButton6.setText("GUARDAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ARTICULO:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CATEGORIA:");

        cbx_categoria11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_categoria11ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("SUBCATEGORIA:");

        cbx_subcategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_subcategoria1ActionPerformed(evt);
            }
        });

        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txt_articulo1.setText("SELECCIONE...");
        txt_articulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_articulo1MousePressed(evt);
            }
        });
        txt_articulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_articulo1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PRODUCTO"));

        txta_descripcion.setColumns(20);
        txta_descripcion.setRows(5);
        jScrollPane1.setViewportView(txta_descripcion);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("DESCRIPCION :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("NOMBRE DEL PRODUCTO :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("MIN :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("MAX :");

        txt_minimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_minimoKeyTyped(evt);
            }
        });

        txt_maximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_maximoKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("CODIGO DE BARRA:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("BODEGA:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txt_codigo_barra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(42, 42, 42)
                                        .addComponent(txt_maximo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(40, 40, 40))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_minimo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                            .addComponent(cbx_bodega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(txt_nombre_productoConcadenado)))
                    .addComponent(jLabel21))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_productoConcadenado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_bodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_maximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("MARCA:");

        txt_marca1.setText("SELECCIONE...");
        txt_marca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_marca1MousePressed(evt);
            }
        });
        txt_marca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marca1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("IVA:");

        cbx_Iva.setEditable(true);
        cbx_Iva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbx_Iva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        cbx_Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_IvaActionPerformed(evt);
            }
        });

        btn_nombre.setText("GENERAR NOMBRE");
        btn_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nombreActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("PRESENTACION:");

        txt_presentacion.setText("SELECCIONE...");
        txt_presentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_presentacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_presentacionMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel1.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(94, 94, 94)
                .addComponent(jButton6)
                .addGap(153, 153, 153))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(77, 77, 77)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(cbx_subcategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(cbx_categoria11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton7))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel19))
                            .addGap(79, 79, 79)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_presentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_nombre))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_marca1)
                                        .addGap(94, 94, 94)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txt_articulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel20)
                                    .addGap(35, 35, 35)
                                    .addComponent(cbx_Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_categoria11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_subcategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_articulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        try {
//            Long idIva = null;
//            if (cbx_Iva.getSelectedItem().toString().equals("SI")) {
//////                producto 
//                listIva = crudIva.listarIvaActivo(1);
//                for (int i = 0; i < listIva.size(); i++) {
//                    idIva = listIva.get(i).getId_iva();
//                }
//            } else {
//                idIva = Long.valueOf(4);
//            }
//            java.util.Date date = new java.util.Date();
//
//            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
//            java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
//
//            producto.setId_iva(idIva);
//            producto.setNombre_producto1(txt_nombre_productoConcadenado.getText());
//            producto.setCodigo_barra(txt_codigo_barra.getText());
//            producto.setEstado('A');
//            producto.setUsuario_creacion("YO");
//            producto.setDescrpcion(txta_descripcion.getText());
//            producto.setCodigo_barra(txt_codigo_barra.getText());
////            producto.setId_presentacion(objPresentacion.getId_presentacion());
////            producto.setPrecio(Double.valueOf(txtPrecio.getText()));
//            producto.setPrecio(0.0);
//            producto.setIva(cbx_Iva.getSelectedItem().toString());
//            producto.setMinimo(Long.valueOf(txt_minimo.getText()));
//            producto.setMaximo(Long.valueOf(txt_maximo.getText()));
//            Long id_bodega = IdBodega(cbx_bodega.getSelectedItem().toString());
//            producto.setId_bodega(id_bodega);
//            producto.setF_creacion(sqlTime);
//            String o = crudProd.insertarProducto(1, producto);
////            model_pdt_producto_join id = crudProd.ObtenerIdProducto(1, sqlTime.toString());
//            String f = crudInv.InsertarProductoInventario(id.getId_producto(), 1, id_bodega);
//            if (o.equals("GUARDADO EXITOSAMENTE")) {
//                JOptionPane.showMessageDialog(null, o);
//                setVisible(false);
//            } else {
//                JOptionPane.showMessageDialog(null, o);
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_jButton6ActionPerformed
    public Long IdBodega(String cbx) {
        Long id = null;
        for (int i = 0; i < listBodega.size(); i++) {
            if(listBodega.get(i).getNombre_bodega()==cbx){
            id = listBodega.get(i).getId_bodega();
            }
        }
        return id;
    }
    private void cbx_categoria11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_categoria11ActionPerformed
        try {
            model_pdt_categoria id = ObtenerModel.ObtenerCategoria(cbx_categoria11.getSelectedItem().toString());
            idCategoria = id.getId_categoria().intValue();
            cagarCbxSubcategoria(idCategoria);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbx_categoria11ActionPerformed

    private void cbx_subcategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_subcategoria1ActionPerformed
        try {
            if (!cbx_subcategoria1.getSelectedItem().toString().equals("")) {
                txt_articulo1.setEnabled(true);

                txt_articulo1.setText("SELECCIONE...");
                txt_marca1.setText("SELECCIONE...");
                txt_presentacion.setText("SELECCIONE...");
//                txt_envase1.setText("SELECCIONE...");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbx_subcategoria1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        agregarCategoria ga = new agregarCategoria(new javax.swing.JFrame(), true);
        ga.setVisible(true);
        cbx_categoria11.removeAllItems();
        cargarCbxCategoria();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        agregarSubCategorias ga = new agregarSubCategorias(new javax.swing.JFrame(), true);
        ga.setVisible(true);
        cagarCbxSubcategoria(idCategoria);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txt_articulo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_articulo1MousePressed
//        int i = 0;
//        String msg = null;
//        if (evt.getClickCount() == 1) {
//            model_pdt_subcategoria_join_subcategoria sub
//                    = ObtenerModel.ObtenerSubcategoria(cbx_subcategoria1.getSelectedItem().toString());
//
//            idSubCategoria = sub.getId_subcategoria().intValue();
//            consultaArticuloEscoger c = new consultaArticuloEscoger(new javax.swing.JFrame(), true, idSubCategoria);
//            c.setVisible(true);
//            objArticulo = c.getObjeto();
//            if (objArticulo != null) {
//                txt_articulo1.setText(objArticulo.getNombre_articulo());
//                txt_marca1.setEnabled(true);
//                txt_marca1.setText("SELECCIONE...");
//            }
//        }
    }//GEN-LAST:event_txt_articulo1MousePressed

    private void txt_articulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_articulo1ActionPerformed

    }//GEN-LAST:event_txt_articulo1ActionPerformed

    private void txt_minimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_minimoKeyTyped
        char car = evt.getKeyChar();

        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_minimoKeyTyped

    private void txt_maximoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maximoKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_maximoKeyTyped

    private void txt_marca1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_marca1MousePressed
//        int i = 0;
//        String msg = null;
//        if (evt.getClickCount() == 1) {
////            model_pdt_articulo sub
////                    = ObtenerModel.ObtenerArticulo(txt_articulo1.getText().toString());
////
////            idArticulo = sub.getId_articulo().intValue();
//
//            consultaMarcaEscoger c = new consultaMarcaEscoger(new javax.swing.JFrame(), true, idArticulo);
//            c.setVisible(true);
//
//            objMarca = c.getObjeto();
//            txt_marca1.setText(objMarca.getNombre());
//            txt_presentacion.setEnabled(true);
//        }
    }//GEN-LAST:event_txt_marca1MousePressed

    private void txt_marca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marca1ActionPerformed

    private void cbx_IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_IvaActionPerformed
        //        IVA = cbxIva.getSelectedItem().toString();
        //        System.out.println("iba: " + IVA);
    }//GEN-LAST:event_cbx_IvaActionPerformed

    private void btn_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nombreActionPerformed

        //        if (!txt_marca.getText().equals("SELECCIONE...")) {
//        System.out.println("**");
        txt_nombre_productoConcadenado.setText(txt_articulo1.getText() + " DE " + txt_marca1.getText() + " "
                + txt_presentacion.getText());
        //        }
    }//GEN-LAST:event_btn_nombreActionPerformed

    private void txt_presentacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_presentacionMousePressed
        int i = 0;
        String msg = null;
        if (evt.getClickCount() == 1) {
//            model_pdt_marca sub
//                    = ObtenerModel.ObtenerMarca(objMarca.getNombre());

//            idMarca = sub.getId_marca().intValue();
//            System.out.println("id ms" + idMarca);
            consultaPresentacion c = new consultaPresentacion(new javax.swing.JFrame(), true, idMarca);
            c.setVisible(true);
            objPresentacion = c.obtenerObj();
            if (objPresentacion != null) {
                txt_presentacion.setText("ENVASE: " + objPresentacion.getNombre_envase() + " MEDIDA: " + objPresentacion.getNombre_medida());
                btn_nombre.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txt_presentacionMousePressed

    private void txt_presentacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_presentacionMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_presentacionMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCuenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCuenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCuenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCuenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregarProductoCuenca dialog = new agregarProductoCuenca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nombre;
    private javax.swing.JComboBox<String> cbx_Iva;
    private javax.swing.JComboBox<String> cbx_bodega;
    private javax.swing.JComboBox<String> cbx_categoria11;
    private javax.swing.JComboBox<String> cbx_subcategoria1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_articulo1;
    private javax.swing.JTextField txt_codigo_barra;
    private javax.swing.JTextField txt_marca1;
    private javax.swing.JTextField txt_maximo;
    private javax.swing.JTextField txt_minimo;
    private javax.swing.JTextField txt_nombre_productoConcadenado;
    private javax.swing.JTextField txt_presentacion;
    private javax.swing.JTextArea txta_descripcion;
    // End of variables declaration//GEN-END:variables
}
