/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.venta;

import ec.com.cp.controler.ctr_inv_inventario;
import ec.com.cp.controler.ctr_seg_cliente;
import ec.com.cp.controler.ctr_ven_cabecera_venta;
import ec.com.cp.controler.ctr_ven_detalle_venta;
import ec.com.cp.model.join.model_emp_empresa_join;
import ec.com.cp.model.join.model_inv_inventario_join;
import ec.com.cp.model.join.model_seg_cliente_join;
import ec.com.cp.model.join.model_seg_usuario_join;
import ec.com.cp.model.model_ven_cabecera_venta;
import ec.com.cp.model.model_ven_detalle_venta;
import ec.com.cp.tabla.Tabla_venta;
import ec.com.cp.util.Formato_Numeros;
import ec.com.cp.view.clientes.ConsultaCliente;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Venta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venta
     */
    model_inv_inventario_join objStock;
    int cantidad, cantidadModi, idCliente, id_uni, cantidadStock, Cont = 1;
    Double precio, precioIva, total, descuento, subtotal;
    Double VGTsubtotal, VGTtotal, VGTiva, VGTdescuento;
    List<model_ven_detalle_venta> listaDetFactura = new ArrayList<model_ven_detalle_venta>();
//////////8
    List<model_inv_inventario_join> ListProdVent2 = null;
    ctr_inv_inventario selectProdVent2 = new ctr_inv_inventario();
///////////////////
    List<model_inv_inventario_join> ListProdVent = null;
    ctr_inv_inventario selectProdVent = new ctr_inv_inventario();

    ArrayList<model_seg_cliente_join> listCliente;
    ctr_seg_cliente crudCliente = new ctr_seg_cliente();

    model_seg_cliente_join objCliente;
//
    model_emp_empresa_join objEmpresa;
    model_seg_usuario_join objUsuario;
//
    ctr_ven_cabecera_venta crudCabVenta = new ctr_ven_cabecera_venta();
    ctr_ven_detalle_venta crudDetalleVenta = new ctr_ven_detalle_venta();
//

    ctr_inv_inventario crudInv = new ctr_inv_inventario();
    List<model_inv_inventario_join> listaInventario;

    public Venta() {
        initComponents();
    }

    public Venta(java.awt.Frame parent, boolean modal, model_emp_empresa_join empresa, model_seg_usuario_join usuario) {
        initComponents();
        this.setLocation(250, 15);
        objEmpresa = empresa;
        objUsuario = usuario;
        cargarDatosEmp();
        consumidorFinal();
    }

    public void cargarDatosEmp() {
        txt_empresa.setText(objEmpresa.getNombre_comercial());
    }

    public void CargarCliente2() {
        listCliente = crudCliente.listarClientesCedula(1, txtIdentificacion.getText());
        for (int i = 0; i < listCliente.size(); i++) {
            txtIdentificacion.setText(listCliente.get(i).getCedula());
//            txtApellido.setText(listCliente.get(i).getNombre());
            txtNombre.setText(listCliente.get(i).getNombre());
            txt_idCliente.setText(listCliente.get(i).getId_persona().toString());
            txtEmail.setText(listCliente.get(i).getEmail());
            txtTelefono.setText(listCliente.get(i).getTelefono());
            txtCelular.setText(listCliente.get(i).getCelular());
            txtDireccion.setText(listCliente.get(i).getDireccion());
        }
//        Tablas.listarClientes(listCliente, tba_Clientes);0930981110
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txt_idCliente = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbx_FormaPago = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tba_detalle_venta = new javax.swing.JTable();
        btn_agregar_prod = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtIva = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_empresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DATOS DEL CLIENTE:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txt_idCliente.setEditable(false);
        txt_idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idClienteActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("DIRECCION:");

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Nª: ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("NOMBRE:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("FORMA PAGO :");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("TELEFONO: ");

        cbx_FormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CREDITO" }));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Codigo:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("CORREO: ");

        txtIdentificacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jButton4.setText("CLIENTE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("CELULAR:");

        txtCelular.setEditable(false);
        txtCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        jButton5.setText("FINAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(269, 269, 269)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addComponent(cbx_FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCelular))
                    .addComponent(jButton5))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel18))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(txtNombre)))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(12, 12, 12)
                .addComponent(cbx_FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_idCliente)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(85, 85, 85)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DETALLE DE FACTURA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tba_detalle_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tba_detalle_venta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tba_detalle_venta.setRowHeight(20);
        tba_detalle_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tba_detalle_ventaMousePressed(evt);
            }
        });
        tba_detalle_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tba_detalle_ventaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tba_detalle_ventaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tba_detalle_venta);

        btn_agregar_prod.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar_prod.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        btn_agregar_prod.setForeground(new java.awt.Color(1, 1, 1));
        btn_agregar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add16.png"))); // NOI18N
        btn_agregar_prod.setText("AGREGAR");
        btn_agregar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_prodActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel13.setText("SUBTOTAL: ");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel16.setText("DESCUENTO:");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel14.setText("IVA  : ");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL: ");

        txtTotal.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIva.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtIva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDescuento.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSubtotal.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSubtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar32.png"))); // NOI18N
        jButton1.setText("   SALIR   ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add32.png"))); // NOI18N
        jButton2.setText("   NUEVO   ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compras.png"))); // NOI18N
        jButton3.setText("   VENDER   ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(btn_agregar_prod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(29, 29, 29))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_agregar_prod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DATOS DE LA EMPRESA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txt_empresa.setEditable(false);
        txt_empresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empresaActionPerformed(evt);
            }
        });
        txt_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_empresaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTA ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tba_detalle_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tba_detalle_ventaMousePressed
        int row = tba_detalle_venta.rowAtPoint(evt.getPoint());
        int col = tba_detalle_venta.columnAtPoint(evt.getPoint());
        if (evt.getClickCount() == 1) {
            if (tba_detalle_venta.getModel().getColumnClass(col).equals(JButton.class)) {
                try {
                    int r = JOptionPane.showConfirmDialog(null, "Desea eliminar este producto?", "", JOptionPane.YES_OPTION);
                    if (r == JOptionPane.YES_OPTION) {
                        int i = tba_detalle_venta.getSelectedRow();

                        listaDetFactura.remove(i);

                        Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);
                        Totalizar();
                        TotalizarIva();
                        TotalizarDescuento();
                        TotalizarSubtotal();
                        Cont = Cont - 1;
                        for (int j = 0; j < listaDetFactura.size(); j++) {
                            Cont = j + 1;
                            listaDetFactura.get(j).setLinea_detalle(Cont);
                        }
                    }
                } catch (Exception e) {
                }
            }
        }

    }//GEN-LAST:event_tba_detalle_ventaMousePressed

    private void tba_detalle_ventaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tba_detalle_ventaKeyReleased
        try {
//            char c = evt.getKeyChar();
//            if (c < '0' || c > '9') {
//                evt.consume();
//            } else {
            int i = tba_detalle_venta.getSelectedRow();
            Double descuentoT = 0.00;

            String valor = (String) tba_detalle_venta.getValueAt(i, 3);
            char o = valor.charAt(0);
            if (o < '0' || o > '9') {
                System.out.println("error " + o);
                JOptionPane.showMessageDialog(null, "Valor Incorrecto!");
                listaDetFactura.get(i).setCantidad(1);
                Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);

            } else {
                System.out.println("puedes ");
//            }
                int cantidadMod = Integer.valueOf(valor);

                cantidadModi = cantidadMod;
                Long id = (Long) tba_detalle_venta.getValueAt(i, 1);

                ListProdVent = selectProdVent.ListaInventarioJoinStockVenta();
                for (int j = 0; j < ListProdVent.size(); j++) {
                    if (ListProdVent.get(j).getId_producto().equals(id)) {
                        int ca = Integer.valueOf(ListProdVent.get(j).getCantidad().intValue());
//                        int out = cantidadMod.compareTo(ca);
                        if (cantidadMod > ca) {
//                        int out = cantidadMod.compareTo(ca);
//                        if (out == 1) {
                            JOptionPane.showMessageDialog(null, "Verifique Stock");
                            listaDetFactura.get(i).setCantidad(1);
                            Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);

                        } else {
                            System.out.println("can t " + cantidadMod);
                            if (cantidadMod > 0) {
                                String ivaS = tba_detalle_venta.getValueAt(i, 6).toString();
                                Double ivaT = Double.valueOf(ivaS.replace(",", "."));
                                String precioS = tba_detalle_venta.getValueAt(i, 4).toString();
                                Double precioT = Double.valueOf(precioS.replace(",", "."));
//                        String descuentoS = tba_detalle.getValueAt(i, 5).toString();
//                        Double descuentoT = Double.valueOf(descuentoS.replace(",", "."));
                                ListProdVent2 = selectProdVent2.ListaInventarioJoinStockVenta();
                                for (int k = 0; k < ListProdVent2.size(); k++) {
//                            System.out.println("lista /// " + ListProdVent2.get(k).getValor_descuento());
                                    if (ListProdVent2.get(k).getId_producto() == ListProdVent.get(j).getId_producto()) {
//                                System.out.println("valor " + ListProdVent2.get(k).getValor_descuento());
                                        descuentoT = ListProdVent2.get(k).getValor_descuento();
                                    }
                                }

                                Double IvaMod = calcularIvaItemCantMod(cantidadModi, ivaT, precioT);
                                Double Desc = calcularDescuentoItemCantMod(cantidadModi, descuentoT);
                                Double subt = calcularSubtotalItemCantMod(cantidadModi, precioT);
                                Double total = calcularTotalItemCantMod(cantidadModi, IvaMod, Desc, precioT);

                                listaDetFactura.get(i).setCantidad(cantidadMod);
                                listaDetFactura.get(i).setIva(IvaMod);
                                listaDetFactura.get(i).setSub_total(subt);
                                listaDetFactura.get(i).setTotal(total);
                                listaDetFactura.get(i).setDecuento(Desc);
//                                Tablas.llenarDetalleVenta(tba_detalle, listaDetFactura);
                                Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);

                                Totalizar();
                                TotalizarIva();
                                TotalizarDescuento();
                                TotalizarSubtotal();
                                /**/

                            } else {
                                JOptionPane.showMessageDialog(null, "Valor Incorrecto!");
                                listaDetFactura.get(i).setCantidad(1);
                                Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);

                            }
                        }/**/

                    }/**/

                }/**/
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tba_detalle_ventaKeyReleased
    private void Totalizar() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetFactura.get(i).getTotal();
                t += p;
//                Formato_Numeros.formatoNumero(t.toString());
                VGTtotal = t;
                txtTotal.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtTotal.setText(t.toString());
            }
        }
    }

    private void TotalizarIva() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetFactura.get(i).getIva();
                t += p;
//                t=Double.valueOf(Formato_Numeros.formatoNumero(t.toString()));
                VGTiva = t;
                txtIva.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtIva.setText(t.toString());
            }
        }
    }

    private void TotalizarDescuento() {
        Double t = 0.0;
        Double p = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                p = listaDetFactura.get(i).getDecuento();
                t += p;
//                Formato_Numeros.formatoNumero(t.toString());
                VGTdescuento = t;
                txtDescuento.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtDescuento.setText(t.toString());
            }
        }
    }

    private void TotalizarSubtotal() {
        Double t = 0.0;
        Double p = 0.0;
        Double pre = 0.0;
        int cant;
        Double subtotal = 0.0;
        if (tba_detalle_venta.getRowCount() > 0) {
            for (int i = 0; i < tba_detalle_venta.getRowCount(); i++) {
                pre = listaDetFactura.get(i).getPrecio_unitario();
                cant = listaDetFactura.get(i).getCantidad();

                p = listaDetFactura.get(i).getSub_total();
                t += p;
                VGTsubtotal = t;
                txtSubtotal.setText(Formato_Numeros.formatoNumero(t.toString()));
//                txtSubtotal.setText(t.toString());
            }
        }
    }

    public Double calcularIvaItemCantMod(int cantMod, Double posicionIva, Double posicionPrecio) {

//        BigInteger cant;
        Double pre;
        Double precioIva2 = null;
        String aplica = objStock.getIva_string();

        if (posicionIva != 0.0) {
//            cant = cantidad;
            pre = posicionPrecio;
            precioIva2 = (cantMod * pre) * 12 / 100;
        } else {
            precioIva2 = 0.0;
        }
        return precioIva2;
    }

    public Double calcularDescuentoItemCantMod(int cantMod, Double descuento) {
        Double descuent = null;
        descuent = cantMod * descuento;
        return descuent;
    }

    public Double calcularSubtotalItemCantMod(int cantMod, Double PrecioIva) {
        Double subto = null;
        subto = cantMod * PrecioIva;
        return subto;
    }

    public Double calcularTotalItemCantMod(int cantMod, Double PrecioIva, Double desc, Double precio) {

        Double pre;
        Double total2;
        /**/
        pre = precio;
        total2 = (cantMod * pre) + PrecioIva - desc;

        return total2;
    }
    private void tba_detalle_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tba_detalle_ventaKeyTyped

    }//GEN-LAST:event_tba_detalle_ventaKeyTyped
    public String validarProductos(String datos) {
        String obj1 = "no";

        for (int i = 0; i < listaDetFactura.size(); i++) {

            if (datos.equals("" + (listaDetFactura.get(i).getId_producto()))) {
                obj1 = "si";

                break;
            }

        }

        return obj1;

    }
    private void btn_agregar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_prodActionPerformed
        try {
            StockVenta ingre = new StockVenta(new javax.swing.JFrame(), true);
            ingre.setVisible(true);

            objStock = ingre.obtObjProdVent();
            if (objStock.equals(null)) {
                JOptionPane.showMessageDialog(rootPane, "SELECCIONE!");
            } else {
                if (validarProductos("" + (objStock.getId_producto())).equals("si")) {
                    JOptionPane.showMessageDialog(rootPane, "El producto ya se fue seleccionado!");
                } else {
                    model_ven_detalle_venta detalle = new model_ven_detalle_venta();
                    cantidad = 1;
                    precio = objStock.getValor_venta();
                    precioIva = calcularIvaItem();
                    descuento = objStock.getValor_descuento();
                    System.out.println(" " + precioIva);
                    detalle.setId_producto(objStock.getId_producto());
                    detalle.setDescripcion(objStock.getNombre_producto());
                    detalle.setCantidad(cantidad);
                    detalle.setDecuento(descuento);
                    detalle.setIva(precioIva);
                    detalle.setPrecio_unitario(objStock.getValor_venta());
                    subtotal = calcularSubtotal();
                    total = calcularTotalItem();
                    detalle.setSub_total(subtotal);
                    detalle.setTotal(total);
                    detalle.setEstado('A');

                    listaDetFactura.add(detalle);
                    for (int i = 0; i < listaDetFactura.size(); i++) {
                        Cont = i + 1;
                        detalle.setLinea_detalle(Cont);
                    }

                    Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);
                    Totalizar();
                    TotalizarIva();
                    TotalizarDescuento();
                    TotalizarSubtotal();
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_agregar_prodActionPerformed
    public Double calcularIvaItem() {
        int cant;
        Double pre;
        Double precioIva = null;
        String aplica = objStock.getIva_string();
        if (aplica.equals("SI")) {
            cant = cantidad;
            pre = precio;
            System.out.println("precio " + pre);
            precioIva = (cant * pre) * 12 / 100;
        } else {
            precioIva = 0.0;
        }
        return precioIva;
    }

    public Double calcularSubtotal() {
        int cant;
        Double pre;
        Double subt;
        cant = cantidad;
        pre = precio;
        subt = cant * pre;

        return subt;
    }

    public Double calcularTotalItem() {
        int cant;
        Double pre;
        Double preIva;
        Double total2;
        Double desc;
        /**/
        preIva = calcularIvaItem();
        cant = cantidad;
        pre = precio;
        desc = descuento;
        total2 = (cant * pre) + preIva - desc;

        return total2;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged

    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

    }//GEN-LAST:event_jLabel1MousePressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped

    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CargarCliente2();
        }
    }//GEN-LAST:event_txtIdentificacionKeyPressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ConsultaCliente cc = new ConsultaCliente(new javax.swing.JFrame(), true);
            cc.setVisible(true);
            objCliente = cc.obtenerObjCliente();

            txtIdentificacion.setText(objCliente.getCedula());
//            txtApellido.setText(objCliente.getNombre());
            txtNombre.setText(objCliente.getNombre());
            txt_idCliente.setText(objCliente.getId_persona().toString());
            txtEmail.setText(objCliente.getEmail());
            txtTelefono.setText(objCliente.getTelefono());
            txtCelular.setText(objCliente.getCelular());
            txtDireccion.setText(objCliente.getDireccion());
//            txtTipoIdent.setText(Clientes.getIdTipoIndentificacion().getNombreIdentificacion());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idClienteActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txt_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empresaActionPerformed

    private void txt_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_empresaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empresaKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if ("0.0".equals(txtTotal.getText().toString())) {
            JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS!");
        } else {
            int r = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Vender?", "", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                java.util.Date date = new java.util.Date();

                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
                model_ven_cabecera_venta cabFact = new model_ven_cabecera_venta();

                cabFact.setId_cliente(Long.valueOf(txt_idCliente.getText()));
                cabFact.setId_sucursal(objEmpresa.getId_sucursal());
                cabFact.setEstado('A');
                cabFact.setForma_pago(cbx_FormaPago.getSelectedItem().toString());
                cabFact.setTotal_subtotal(VGTsubtotal);
                cabFact.setTotal_iva(VGTiva);
                cabFact.setTotal_descuento(VGTdescuento);
                cabFact.setTotal_facturado(VGTtotal);
                cabFact.setUsuario_creacion(objUsuario.getNomb_usuario());
                cabFact.setF_creacion(sqlTime);

                String c = crudCabVenta.insertarCabeceraVenta(cabFact, 1);
                try {
                    for (int i = 0; i < listaDetFactura.size(); i++) {
                        model_ven_detalle_venta detalleVenta = new model_ven_detalle_venta();
                        detalleVenta.setLinea_detalle(listaDetFactura.get(i).getLinea_detalle());
                        detalleVenta.setId_producto(listaDetFactura.get(i).getId_producto());
                        detalleVenta.setCantidad(listaDetFactura.get(i).getCantidad());
                        detalleVenta.setDescripcion(listaDetFactura.get(i).getDescripcion());
                        detalleVenta.setPrecio_unitario(listaDetFactura.get(i).getPrecio_unitario());
                        detalleVenta.setSub_total(listaDetFactura.get(i).getSub_total());
                        detalleVenta.setIva(listaDetFactura.get(i).getIva());
                        detalleVenta.setDecuento(listaDetFactura.get(i).getDecuento());
                        detalleVenta.setTotal(listaDetFactura.get(i).getTotal());
                        detalleVenta.setEstado(listaDetFactura.get(i).getEstado());

                        String out = crudDetalleVenta.insertarDetalleVenta(detalleVenta, Long.valueOf(txt_idCliente.getText()),
                                objEmpresa.getId_sucursal(), VGTtotal, sqlTime.toString());

                        guardarKardex(detalleVenta.getId_producto(), listaDetFactura.get(i).getCantidad());
                        JOptionPane.showMessageDialog(null, out);
                    }
                } catch (Exception e) {
                }

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public void guardarKardex(Long id, int cantVent) {
        int Restcantidad = 0;
        listaInventario = crudInv.ListaInventarioJoinTodo();
        for (int i = 0; i < listaInventario.size(); i++) {
            if (listaInventario.get(i).getId_producto().equals(id)) {
                int Stock = listaInventario.get(i).getCantidad().intValue();
                Restcantidad = Stock - cantVent;
                System.out.println("Stock :" + Stock);
                System.out.println("cantVent :" + cantVent);
                System.out.println("resta :" + Restcantidad);
            }
        }

        objStock.setCantidad(Long.valueOf(Restcantidad));
        objStock.setId_producto(id);
        String cant = crudInv.ActualizarCantidadVenta(objStock, 1);
    }

    public void consumidorFinal() {
        listCliente = crudCliente.listarClientes(1);
        for (int i = 0; i < listCliente.size(); i++) {
            System.out.println("+" + listCliente.get(i).getId_persona());
            if (listCliente.get(i).getId_persona() == 1) {
                System.out.println("**");
                txtIdentificacion.setText(listCliente.get(i).getCedula());
                txtNombre.setText(listCliente.get(i).getNombre());
                txt_idCliente.setText(listCliente.get(i).getId_persona().toString());
                txtEmail.setText(listCliente.get(i).getEmail());
                txtTelefono.setText(listCliente.get(i).getTelefono());
                txtCelular.setText(listCliente.get(i).getCelular());
                txtDireccion.setText(listCliente.get(i).getDireccion());

            }
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        consumidorFinal();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void limpiar() {
        consumidorFinal();
        listaDetFactura.clear();
        Tabla_venta.llenarDetalleVenta(tba_detalle_venta, listaDetFactura);
//        Tablas.llenarDetalleVenta(tba_detalle, listaDetFactura);
        txtSubtotal.setText("");
        txtDescuento.setText("");
        txtIva.setText("");
        txtTotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_prod;
    private javax.swing.JComboBox<String> cbx_FormaPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tba_detalle_venta;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JLabel txtDescuento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JLabel txtIva;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_idCliente;
    // End of variables declaration//GEN-END:variables
}
