/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cp.view.categoria;

import ec.com.cp.controler.ctr_pdt_articulo;
import ec.com.cp.controler.ctr_pdt_categoria;
import ec.com.cp.controler.ctr_pdt_marca;
import ec.com.cp.controler.ctr_pdt_producto;
import ec.com.cp.controler.ctr_pdt_subcategoria;
import ec.com.cp.model.join.model_pdt_subcategoria_join_subcategoria;
import ec.com.cp.model.model_pdt_articulo_dos;
import ec.com.cp.model.model_pdt_categoria;
import ec.com.cp.model.model_pdt_marca_dos;
import ec.com.cp.model.model_pdt_producto;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmEditarCategoria extends javax.swing.JDialog {

    /**
     * Creates new form editarCategoria
     */
    int x, y;
    ctr_pdt_categoria crud = new ctr_pdt_categoria();
    ctr_pdt_subcategoria crudSubCat = new ctr_pdt_subcategoria();
    ctr_pdt_subcategoria control = new ctr_pdt_subcategoria();
    ctr_pdt_marca ctrMarca = new ctr_pdt_marca();
    ctr_pdt_articulo ctrArt = new ctr_pdt_articulo();
    ctr_pdt_producto ctrPro = new ctr_pdt_producto();

    model_pdt_categoria categoria;
    model_pdt_subcategoria_join_subcategoria subcategoria = new model_pdt_subcategoria_join_subcategoria();
    model_pdt_marca_dos marca = new model_pdt_marca_dos();
    model_pdt_articulo_dos articulo = new model_pdt_articulo_dos();
    model_pdt_producto producto = new model_pdt_producto();

    String estado = "";

    public FrmEditarCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    public FrmEditarCategoria(java.awt.Frame parent, boolean modal, model_pdt_categoria cat) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        categoria = cat;
        txt_nombre.setText(categoria.getNombre());
//        btnBoton.setVisible(false);
        btn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        txt_nombre.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txt_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nombreFocusLost(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disquete guardar 32.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar32.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATEGORIA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        btnBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inactivar 32.png"))); // NOI18N
        btnBoton.setText("INACTIVAR");
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(btnBoton)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(btnBoton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreFocusLost
        txt_nombre.setText(txt_nombre.getText().toUpperCase());
    }//GEN-LAST:event_txt_nombreFocusLost

    public void btn() {
        estado = "" + categoria.getEstado();
        if ("A".equals(estado)) {
            btnBoton.setText("INACTIVAR");
        }
        if ("I".equals(estado)) {
            btnBoton.setText("ACTIVAR");
        }
    }
    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void actualizar() {
        try {
            categoria.setId_categoria(categoria.getId_categoria());
            categoria.setNombre(txt_nombre.getText());
            categoria.setUsuario_actulizacion("yo");
            String o = crud.actualizarCategoria(categoria);
            JOptionPane.showMessageDialog(null, o);
            setVisible(false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel1MouseDragged
    public void proceso() {
        ArrayList<model_pdt_subcategoria_join_subcategoria> lista = new ArrayList<>();
        lista = control.listarSubCategorias(1);
        Long idSub;
        ArrayList<model_pdt_marca_dos> listMarca = ctrMarca.listarMarcas(1);
        Long idMar;
        ArrayList<model_pdt_articulo_dos> listArticulo = ctrArt.listarArticulos(1);
        Long idArt;
        ArrayList<model_pdt_producto> listPro = ctrPro.listarProducto(1);
        Long idPro;

        for (int i = 0; i < lista.size(); i++) {
            if (Objects.equals(lista.get(i).getId_categoria(), categoria.getId_categoria())) {

                idSub = lista.get(i).getId_subcategoria();
                subcategoria.setId_subcategoria(idSub);
                subcategoria.setEstado(estado.charAt(0));
                subcategoria.setUsuario_actulizacion("YO");

                String msgSub = crudSubCat.activarInactivarSubCategoria(subcategoria);
                System.out.println("id sub: " + idSub + estado.charAt(0));
                for (int m = 0; m < listMarca.size(); m++) {
                    if (Objects.equals(listMarca.get(m).getId_subcategoria(), idSub)) {

                        idMar = listMarca.get(m).getId_marca();
                        marca.setId_marca(idMar);
                        marca.setEstado(estado.charAt(0));
                        marca.setU_actualizacion("YO");

                        String msgMar = ctrMarca.activarInactivarMarca(marca);
                        System.out.println("id marca: " + listMarca.get(m).getId_marca());
                        for (int a = 0; a < listArticulo.size(); a++) {
                            if (Objects.equals(listArticulo.get(a).getId_marca(), idMar)) {

                                idArt = listArticulo.get(a).getId_articulo();
                                articulo.setId_articulo(idArt);
                                articulo.setEstado(estado.charAt(0));
                                articulo.setUsuario_actulizacion("YO");

                                String msgArt = ctrArt.activarInactivarArticulo(articulo);
                                System.out.println("id articulo: " + listArticulo.get(a).getId_articulo());
                                for (int p = 0; p < listPro.size(); p++) {
                                    if (Objects.equals(listPro.get(p).getId_articulo(), idArt)) {

                                        idPro = listPro.get(p).getId_producto();
                                        producto.setId_producto(idPro);
                                        producto.setEstado(estado.charAt(0));
                                        producto.setUsuario_actulizacion("YO");

                                        String msgPro = ctrPro.activarInactivarProducto(producto);
                                        System.out.println("id producto: " + idPro);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed
    public void activaInactivar() {
        String boton = btnBoton.getText();
        if ("INACTIVAR".equals(boton) || "ACTIVAR".equals(boton)) {
            JOptionPane.showMessageDialog(this, "RECUERDE QUE SE " + boton + "A EN CASCADA TODA LO CONTENIDO EN ESTA CATEGORIA!");
            int r = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE " + boton + " A: " + categoria.getNombre() + "?", "", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {

                if ("INACTIVAR".equals(boton)) {
                    estado = "I";
                }
                if ("ACTIVAR".equals(boton)) {
                    estado = "A";
                }
                categoria.setId_categoria(categoria.getId_categoria());
                categoria.setEstado(estado.charAt(0));
                categoria.setUsuario_actulizacion("YO");
                try {
                    String msg = crud.activarInactivarCategoria(categoria);
                    proceso();
                    JOptionPane.showMessageDialog(this, msg);


                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(this, e);
                }
                setVisible(false);
            } else {
            }
        }
    }
    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
        activaInactivar();
    }//GEN-LAST:event_btnBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEditarCategoria dialog = new FrmEditarCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
